// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="display_float_display_float,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.287000,HLS_SYN_LAT=39,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6057,HLS_SYN_LUT=5976,HLS_VERSION=2023_2}" *)

module display_float (
        ap_clk,
        ap_rst,
        acc,
        seven_segment_data,
        seven_segment_enable
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [31:0] acc;
output  [7:0] seven_segment_data;
output  [3:0] seven_segment_enable;

reg[7:0] seven_segment_data;
reg[3:0] seven_segment_enable;

reg   [1:0] state;
reg   [31:0] timer;
reg   [3:0] seven_segment_code_address0;
reg    seven_segment_code_ce0;
wire   [7:0] seven_segment_code_q0;
wire   [3:0] seven_segment_code_address1;
reg    seven_segment_code_ce1;
wire   [7:0] seven_segment_code_q1;
wire   [3:0] seven_segment_code_address2;
reg    seven_segment_code_ce2;
wire   [7:0] seven_segment_code_q2;
reg   [31:0] acc_read_reg_679;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] acc_read_reg_679_pp0_iter1_reg;
reg   [31:0] acc_read_reg_679_pp0_iter2_reg;
reg   [31:0] acc_read_reg_679_pp0_iter3_reg;
reg   [31:0] acc_read_reg_679_pp0_iter4_reg;
reg   [31:0] acc_read_reg_679_pp0_iter5_reg;
reg   [31:0] acc_read_reg_679_pp0_iter6_reg;
wire   [0:0] tmp_2_fu_256_p3;
reg   [0:0] tmp_2_reg_684;
reg   [31:0] tmp_reg_689;
reg   [31:0] tmp_1_reg_694;
wire   [1:0] state_load_load_fu_322_p1;
reg   [1:0] state_load_reg_699;
reg   [1:0] state_load_reg_699_pp0_iter1_reg;
reg   [1:0] state_load_reg_699_pp0_iter2_reg;
reg   [1:0] state_load_reg_699_pp0_iter3_reg;
reg   [1:0] state_load_reg_699_pp0_iter4_reg;
reg   [1:0] state_load_reg_699_pp0_iter5_reg;
reg   [1:0] state_load_reg_699_pp0_iter6_reg;
reg   [1:0] state_load_reg_699_pp0_iter7_reg;
reg   [1:0] state_load_reg_699_pp0_iter8_reg;
reg   [1:0] state_load_reg_699_pp0_iter9_reg;
reg   [1:0] state_load_reg_699_pp0_iter10_reg;
reg   [1:0] state_load_reg_699_pp0_iter11_reg;
reg   [1:0] state_load_reg_699_pp0_iter12_reg;
reg   [1:0] state_load_reg_699_pp0_iter13_reg;
reg   [1:0] state_load_reg_699_pp0_iter14_reg;
reg   [1:0] state_load_reg_699_pp0_iter15_reg;
reg   [1:0] state_load_reg_699_pp0_iter16_reg;
reg   [1:0] state_load_reg_699_pp0_iter17_reg;
reg   [1:0] state_load_reg_699_pp0_iter18_reg;
reg   [1:0] state_load_reg_699_pp0_iter19_reg;
reg   [1:0] state_load_reg_699_pp0_iter20_reg;
reg   [1:0] state_load_reg_699_pp0_iter21_reg;
reg   [1:0] state_load_reg_699_pp0_iter22_reg;
reg   [1:0] state_load_reg_699_pp0_iter23_reg;
reg   [1:0] state_load_reg_699_pp0_iter24_reg;
reg   [1:0] state_load_reg_699_pp0_iter25_reg;
reg   [1:0] state_load_reg_699_pp0_iter26_reg;
reg   [1:0] state_load_reg_699_pp0_iter27_reg;
reg   [1:0] state_load_reg_699_pp0_iter28_reg;
reg   [1:0] state_load_reg_699_pp0_iter29_reg;
reg   [1:0] state_load_reg_699_pp0_iter30_reg;
reg   [1:0] state_load_reg_699_pp0_iter31_reg;
reg   [1:0] state_load_reg_699_pp0_iter32_reg;
reg   [1:0] state_load_reg_699_pp0_iter33_reg;
reg   [1:0] state_load_reg_699_pp0_iter34_reg;
reg   [1:0] state_load_reg_699_pp0_iter35_reg;
reg   [1:0] state_load_reg_699_pp0_iter36_reg;
reg   [1:0] state_load_reg_699_pp0_iter37_reg;
reg   [1:0] state_load_reg_699_pp0_iter38_reg;
wire   [31:0] val_fu_400_p3;
reg   [31:0] val_reg_703;
reg   [28:0] trunc_ln_reg_715;
wire   [31:0] grp_fu_203_p1;
reg   [31:0] conv1_reg_720;
wire   [31:0] grp_fu_185_p2;
reg   [31:0] b_reg_725;
wire   [31:0] grp_fu_193_p2;
reg   [31:0] dc_reg_730;
reg   [31:0] dc_reg_730_pp0_iter18_reg;
reg   [31:0] dc_reg_730_pp0_iter19_reg;
reg   [31:0] dc_reg_730_pp0_iter20_reg;
reg   [31:0] dc_reg_730_pp0_iter21_reg;
reg   [31:0] dc_reg_730_pp0_iter22_reg;
reg   [31:0] dc_reg_730_pp0_iter23_reg;
reg   [31:0] dc_reg_730_pp0_iter24_reg;
reg   [31:0] dc_reg_730_pp0_iter25_reg;
wire   [22:0] trunc_ln342_1_fu_443_p1;
reg   [22:0] trunc_ln342_1_reg_736;
wire   [0:0] tmp_3_fu_457_p3;
reg   [0:0] tmp_3_reg_741;
wire   [8:0] select_ln71_2_fu_475_p3;
reg   [8:0] select_ln71_2_reg_746;
reg   [31:0] val_1_reg_751;
reg   [3:0] c_reg_756;
reg   [3:0] c_reg_756_pp0_iter20_reg;
reg   [3:0] c_reg_756_pp0_iter21_reg;
reg   [3:0] c_reg_756_pp0_iter22_reg;
reg   [3:0] c_reg_756_pp0_iter23_reg;
reg   [3:0] c_reg_756_pp0_iter24_reg;
reg   [3:0] c_reg_756_pp0_iter25_reg;
reg   [3:0] c_reg_756_pp0_iter26_reg;
reg   [3:0] c_reg_756_pp0_iter27_reg;
reg   [3:0] c_reg_756_pp0_iter28_reg;
reg   [3:0] c_reg_756_pp0_iter29_reg;
reg   [3:0] c_reg_756_pp0_iter30_reg;
reg   [3:0] c_reg_756_pp0_iter31_reg;
reg   [3:0] c_reg_756_pp0_iter32_reg;
reg   [3:0] c_reg_756_pp0_iter33_reg;
reg   [3:0] c_reg_756_pp0_iter34_reg;
reg   [3:0] c_reg_756_pp0_iter35_reg;
reg   [3:0] c_reg_756_pp0_iter36_reg;
reg   [3:0] c_reg_756_pp0_iter37_reg;
wire   [31:0] grp_fu_206_p1;
reg   [31:0] conv5_reg_761;
wire   [31:0] grp_fu_189_p2;
reg   [31:0] b_1_reg_766;
reg   [7:0] xs_exp_2_reg_771;
wire   [22:0] trunc_ln342_2_fu_556_p1;
reg   [22:0] trunc_ln342_2_reg_777;
wire   [0:0] tmp_6_fu_587_p3;
reg   [0:0] tmp_6_reg_787;
reg   [3:0] tmp_4_reg_792;
reg   [3:0] tmp_5_reg_797;
reg   [7:0] seven_segment_code_load_1_reg_807;
reg    ap_enable_reg_pp0_iter37;
reg   [7:0] seven_segment_code_load_1_reg_807_pp0_iter38_reg;
wire   [6:0] trunc_ln42_fu_666_p1;
reg   [6:0] trunc_ln42_reg_817;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg   [1:0] ap_phi_mux_next_state_4_phi_fu_175_p8;
wire   [1:0] select_ln74_1_fu_379_p3;
wire   [1:0] ap_phi_reg_pp0_iter0_next_state_4_reg_172;
wire   [1:0] next_state_3_fu_350_p3;
wire   [1:0] next_state_2_fu_359_p3;
wire   [1:0] zext_ln21_fu_374_p1;
wire   [63:0] zext_ln27_fu_560_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln42_fu_652_p1;
wire   [63:0] zext_ln57_fu_662_p1;
wire   [63:0] zext_ln72_fu_670_p1;
wire   [31:0] next_timer_1_fu_342_p3;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] zext_ln42_1_fu_675_p1;
wire   [31:0] grp_fu_203_p0;
wire   [31:0] grp_fu_209_p0;
wire   [33:0] grp_fu_209_p1;
wire   [31:0] data_fu_214_p1;
wire   [22:0] trunc_ln342_fu_228_p1;
wire   [24:0] mantissa_fu_232_p4;
wire   [7:0] xs_exp_fu_218_p4;
wire   [8:0] zext_ln317_fu_246_p1;
wire   [8:0] add_ln317_fu_250_p2;
wire   [7:0] sub_ln71_fu_264_p2;
wire  signed [8:0] sext_ln71_fu_270_p1;
wire   [8:0] select_ln71_fu_274_p3;
wire  signed [31:0] sext_ln71_1_fu_282_p1;
wire   [78:0] zext_ln68_fu_242_p1;
wire   [78:0] zext_ln71_fu_286_p1;
wire   [78:0] lshr_ln71_fu_290_p2;
wire   [78:0] shl_ln71_fu_296_p2;
wire   [0:0] next_state_fu_330_p2;
wire   [31:0] next_timer_fu_336_p2;
wire   [0:0] next_state_1_fu_368_p2;
wire   [4:0] grp_fu_406_p1;
wire   [64:0] grp_fu_209_p2;
wire   [4:0] grp_fu_425_p1;
wire   [31:0] data_1_fu_430_p1;
wire   [7:0] xs_exp_1_fu_433_p4;
wire   [8:0] zext_ln317_1_fu_447_p1;
wire   [8:0] add_ln317_1_fu_451_p2;
wire   [7:0] sub_ln71_1_fu_465_p2;
wire  signed [8:0] sext_ln71_2_fu_471_p1;
wire   [24:0] mantissa_1_fu_483_p4;
wire  signed [31:0] sext_ln71_3_fu_496_p1;
wire   [78:0] zext_ln68_1_fu_492_p1;
wire   [78:0] zext_ln71_1_fu_499_p1;
wire   [78:0] lshr_ln71_1_fu_503_p2;
wire   [78:0] shl_ln71_1_fu_509_p2;
wire   [78:0] select_ln71_3_fu_515_p3;
wire   [31:0] grp_fu_198_p2;
wire   [31:0] data_2_fu_542_p1;
wire   [28:0] grp_fu_425_p2;
wire   [24:0] mantissa_2_fu_565_p4;
wire   [8:0] zext_ln317_2_fu_578_p1;
wire   [8:0] add_ln317_2_fu_581_p2;
wire   [7:0] sub_ln71_2_fu_595_p2;
wire  signed [8:0] sext_ln71_4_fu_600_p1;
wire   [8:0] select_ln71_4_fu_604_p3;
wire  signed [31:0] sext_ln71_5_fu_612_p1;
wire   [78:0] zext_ln68_2_fu_574_p1;
wire   [78:0] zext_ln71_2_fu_616_p1;
wire   [78:0] lshr_ln71_2_fu_620_p2;
wire   [78:0] shl_ln71_2_fu_626_p2;
wire   [31:0] grp_fu_406_p2;
wire   [3:0] select_ln71_5_fu_657_p3;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [64:0] grp_fu_209_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 state = 2'd0;
#0 timer = 32'd100000;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
end

display_float_seven_segment_code_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
seven_segment_code_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(seven_segment_code_address0),
    .ce0(seven_segment_code_ce0),
    .q0(seven_segment_code_q0),
    .address1(seven_segment_code_address1),
    .ce1(seven_segment_code_ce1),
    .q1(seven_segment_code_q1),
    .address2(seven_segment_code_address2),
    .ce2(seven_segment_code_ce2),
    .q2(seven_segment_code_q2)
);

display_float_fsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_7_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_read_reg_679_pp0_iter6_reg),
    .din1(conv1_reg_720),
    .ce(1'b1),
    .dout(grp_fu_185_p2)
);

display_float_fsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_7_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(dc_reg_730_pp0_iter25_reg),
    .din1(conv5_reg_761),
    .ce(1'b1),
    .dout(grp_fu_189_p2)
);

display_float_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_reg_725),
    .din1(32'd1092616192),
    .ce(1'b1),
    .dout(grp_fu_193_p2)
);

display_float_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_1_reg_766),
    .din1(32'd1092616192),
    .ce(1'b1),
    .dout(grp_fu_198_p2)
);

display_float_uitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_6_no_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_203_p0),
    .ce(1'b1),
    .dout(grp_fu_203_p1)
);

display_float_uitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_6_no_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(val_1_reg_751),
    .ce(1'b1),
    .dout(grp_fu_206_p1)
);

display_float_mul_32ns_34ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_209_p0),
    .din1(grp_fu_209_p1),
    .ce(1'b1),
    .dout(grp_fu_209_p2)
);

display_float_urem_32ns_5ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
urem_32ns_5ns_32_36_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(val_reg_703),
    .din1(grp_fu_406_p1),
    .ce(1'b1),
    .dout(grp_fu_406_p2)
);

display_float_urem_29ns_5ns_29_33_1 #(
    .ID( 1 ),
    .NUM_STAGE( 33 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 29 ))
urem_29ns_5ns_29_33_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln_reg_715),
    .din1(grp_fu_425_p1),
    .ce(1'b1),
    .dout(grp_fu_425_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_read_reg_679 <= acc;
        acc_read_reg_679_pp0_iter1_reg <= acc_read_reg_679;
        state_load_reg_699 <= state;
        state_load_reg_699_pp0_iter1_reg <= state_load_reg_699;
        tmp_1_reg_694 <= {{shl_ln71_fu_296_p2[55:24]}};
        tmp_2_reg_684 <= add_ln317_fu_250_p2[32'd8];
        tmp_reg_689 <= {{lshr_ln71_fu_290_p2[55:24]}};
        val_reg_703 <= val_fu_400_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_read_reg_679_pp0_iter2_reg <= acc_read_reg_679_pp0_iter1_reg;
        acc_read_reg_679_pp0_iter3_reg <= acc_read_reg_679_pp0_iter2_reg;
        acc_read_reg_679_pp0_iter4_reg <= acc_read_reg_679_pp0_iter3_reg;
        acc_read_reg_679_pp0_iter5_reg <= acc_read_reg_679_pp0_iter4_reg;
        acc_read_reg_679_pp0_iter6_reg <= acc_read_reg_679_pp0_iter5_reg;
        b_1_reg_766 <= grp_fu_189_p2;
        b_reg_725 <= grp_fu_185_p2;
        c_reg_756 <= {{select_ln71_3_fu_515_p3[27:24]}};
        c_reg_756_pp0_iter20_reg <= c_reg_756;
        c_reg_756_pp0_iter21_reg <= c_reg_756_pp0_iter20_reg;
        c_reg_756_pp0_iter22_reg <= c_reg_756_pp0_iter21_reg;
        c_reg_756_pp0_iter23_reg <= c_reg_756_pp0_iter22_reg;
        c_reg_756_pp0_iter24_reg <= c_reg_756_pp0_iter23_reg;
        c_reg_756_pp0_iter25_reg <= c_reg_756_pp0_iter24_reg;
        c_reg_756_pp0_iter26_reg <= c_reg_756_pp0_iter25_reg;
        c_reg_756_pp0_iter27_reg <= c_reg_756_pp0_iter26_reg;
        c_reg_756_pp0_iter28_reg <= c_reg_756_pp0_iter27_reg;
        c_reg_756_pp0_iter29_reg <= c_reg_756_pp0_iter28_reg;
        c_reg_756_pp0_iter30_reg <= c_reg_756_pp0_iter29_reg;
        c_reg_756_pp0_iter31_reg <= c_reg_756_pp0_iter30_reg;
        c_reg_756_pp0_iter32_reg <= c_reg_756_pp0_iter31_reg;
        c_reg_756_pp0_iter33_reg <= c_reg_756_pp0_iter32_reg;
        c_reg_756_pp0_iter34_reg <= c_reg_756_pp0_iter33_reg;
        c_reg_756_pp0_iter35_reg <= c_reg_756_pp0_iter34_reg;
        c_reg_756_pp0_iter36_reg <= c_reg_756_pp0_iter35_reg;
        c_reg_756_pp0_iter37_reg <= c_reg_756_pp0_iter36_reg;
        conv1_reg_720 <= grp_fu_203_p1;
        conv5_reg_761 <= grp_fu_206_p1;
        dc_reg_730 <= grp_fu_193_p2;
        dc_reg_730_pp0_iter18_reg <= dc_reg_730;
        dc_reg_730_pp0_iter19_reg <= dc_reg_730_pp0_iter18_reg;
        dc_reg_730_pp0_iter20_reg <= dc_reg_730_pp0_iter19_reg;
        dc_reg_730_pp0_iter21_reg <= dc_reg_730_pp0_iter20_reg;
        dc_reg_730_pp0_iter22_reg <= dc_reg_730_pp0_iter21_reg;
        dc_reg_730_pp0_iter23_reg <= dc_reg_730_pp0_iter22_reg;
        dc_reg_730_pp0_iter24_reg <= dc_reg_730_pp0_iter23_reg;
        dc_reg_730_pp0_iter25_reg <= dc_reg_730_pp0_iter24_reg;
        select_ln71_2_reg_746 <= select_ln71_2_fu_475_p3;
        seven_segment_code_load_1_reg_807_pp0_iter38_reg <= seven_segment_code_load_1_reg_807;
        state_load_reg_699_pp0_iter10_reg <= state_load_reg_699_pp0_iter9_reg;
        state_load_reg_699_pp0_iter11_reg <= state_load_reg_699_pp0_iter10_reg;
        state_load_reg_699_pp0_iter12_reg <= state_load_reg_699_pp0_iter11_reg;
        state_load_reg_699_pp0_iter13_reg <= state_load_reg_699_pp0_iter12_reg;
        state_load_reg_699_pp0_iter14_reg <= state_load_reg_699_pp0_iter13_reg;
        state_load_reg_699_pp0_iter15_reg <= state_load_reg_699_pp0_iter14_reg;
        state_load_reg_699_pp0_iter16_reg <= state_load_reg_699_pp0_iter15_reg;
        state_load_reg_699_pp0_iter17_reg <= state_load_reg_699_pp0_iter16_reg;
        state_load_reg_699_pp0_iter18_reg <= state_load_reg_699_pp0_iter17_reg;
        state_load_reg_699_pp0_iter19_reg <= state_load_reg_699_pp0_iter18_reg;
        state_load_reg_699_pp0_iter20_reg <= state_load_reg_699_pp0_iter19_reg;
        state_load_reg_699_pp0_iter21_reg <= state_load_reg_699_pp0_iter20_reg;
        state_load_reg_699_pp0_iter22_reg <= state_load_reg_699_pp0_iter21_reg;
        state_load_reg_699_pp0_iter23_reg <= state_load_reg_699_pp0_iter22_reg;
        state_load_reg_699_pp0_iter24_reg <= state_load_reg_699_pp0_iter23_reg;
        state_load_reg_699_pp0_iter25_reg <= state_load_reg_699_pp0_iter24_reg;
        state_load_reg_699_pp0_iter26_reg <= state_load_reg_699_pp0_iter25_reg;
        state_load_reg_699_pp0_iter27_reg <= state_load_reg_699_pp0_iter26_reg;
        state_load_reg_699_pp0_iter28_reg <= state_load_reg_699_pp0_iter27_reg;
        state_load_reg_699_pp0_iter29_reg <= state_load_reg_699_pp0_iter28_reg;
        state_load_reg_699_pp0_iter2_reg <= state_load_reg_699_pp0_iter1_reg;
        state_load_reg_699_pp0_iter30_reg <= state_load_reg_699_pp0_iter29_reg;
        state_load_reg_699_pp0_iter31_reg <= state_load_reg_699_pp0_iter30_reg;
        state_load_reg_699_pp0_iter32_reg <= state_load_reg_699_pp0_iter31_reg;
        state_load_reg_699_pp0_iter33_reg <= state_load_reg_699_pp0_iter32_reg;
        state_load_reg_699_pp0_iter34_reg <= state_load_reg_699_pp0_iter33_reg;
        state_load_reg_699_pp0_iter35_reg <= state_load_reg_699_pp0_iter34_reg;
        state_load_reg_699_pp0_iter36_reg <= state_load_reg_699_pp0_iter35_reg;
        state_load_reg_699_pp0_iter37_reg <= state_load_reg_699_pp0_iter36_reg;
        state_load_reg_699_pp0_iter38_reg <= state_load_reg_699_pp0_iter37_reg;
        state_load_reg_699_pp0_iter3_reg <= state_load_reg_699_pp0_iter2_reg;
        state_load_reg_699_pp0_iter4_reg <= state_load_reg_699_pp0_iter3_reg;
        state_load_reg_699_pp0_iter5_reg <= state_load_reg_699_pp0_iter4_reg;
        state_load_reg_699_pp0_iter6_reg <= state_load_reg_699_pp0_iter5_reg;
        state_load_reg_699_pp0_iter7_reg <= state_load_reg_699_pp0_iter6_reg;
        state_load_reg_699_pp0_iter8_reg <= state_load_reg_699_pp0_iter7_reg;
        state_load_reg_699_pp0_iter9_reg <= state_load_reg_699_pp0_iter8_reg;
        tmp_3_reg_741 <= add_ln317_1_fu_451_p2[32'd8];
        tmp_4_reg_792 <= {{lshr_ln71_2_fu_620_p2[27:24]}};
        tmp_5_reg_797 <= {{shl_ln71_2_fu_626_p2[27:24]}};
        tmp_6_reg_787 <= add_ln317_2_fu_581_p2[32'd8];
        trunc_ln342_1_reg_736 <= trunc_ln342_1_fu_443_p1;
        trunc_ln342_2_reg_777 <= trunc_ln342_2_fu_556_p1;
        trunc_ln42_reg_817 <= trunc_ln42_fu_666_p1;
        trunc_ln_reg_715 <= {{grp_fu_209_p2[64:36]}};
        val_1_reg_751 <= {{select_ln71_3_fu_515_p3[55:24]}};
        xs_exp_2_reg_771 <= {{data_2_fu_542_p1[30:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        seven_segment_code_load_1_reg_807 <= seven_segment_code_q2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state <= ap_phi_mux_next_state_4_phi_fu_175_p8;
        timer <= next_timer_1_fu_342_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 
    == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((state_load_load_fu_322_p1 == 2'd0)) begin
        ap_phi_mux_next_state_4_phi_fu_175_p8 = zext_ln21_fu_374_p1;
    end else if ((state_load_load_fu_322_p1 == 2'd1)) begin
        ap_phi_mux_next_state_4_phi_fu_175_p8 = next_state_2_fu_359_p3;
    end else if ((state_load_load_fu_322_p1 == 2'd2)) begin
        ap_phi_mux_next_state_4_phi_fu_175_p8 = next_state_3_fu_350_p3;
    end else if ((state_load_load_fu_322_p1 == 2'd3)) begin
        ap_phi_mux_next_state_4_phi_fu_175_p8 = select_ln74_1_fu_379_p3;
    end else begin
        ap_phi_mux_next_state_4_phi_fu_175_p8 = ap_phi_reg_pp0_iter0_next_state_4_reg_172;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter38 == 1'b1))) begin
        if ((state_load_reg_699_pp0_iter37_reg == 2'd3)) begin
            seven_segment_code_address0 = zext_ln72_fu_670_p1;
        end else if ((state_load_reg_699_pp0_iter37_reg == 2'd2)) begin
            seven_segment_code_address0 = zext_ln57_fu_662_p1;
        end else begin
            seven_segment_code_address0 = 'bx;
        end
    end else begin
        seven_segment_code_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter38 == 1'b1) & (state_load_reg_699_pp0_iter37_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter38 == 1'b1) & (state_load_reg_699_pp0_iter37_reg == 2'd2)))) begin
        seven_segment_code_ce0 = 1'b1;
    end else begin
        seven_segment_code_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        seven_segment_code_ce1 = 1'b1;
    end else begin
        seven_segment_code_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        seven_segment_code_ce2 = 1'b1;
    end else begin
        seven_segment_code_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1) & (state_load_reg_699_pp0_iter38_reg == 2'd0))) begin
        seven_segment_data = seven_segment_code_load_1_reg_807_pp0_iter38_reg;
    end else if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1) & (state_load_reg_699_pp0_iter38_reg == 2'd1))) begin
        seven_segment_data = zext_ln42_1_fu_675_p1;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1) & (state_load_reg_699_pp0_iter38_reg == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1) & (state_load_reg_699_pp0_iter38_reg == 2'd2)))) begin
        seven_segment_data = seven_segment_code_q0;
    end else begin
        seven_segment_data = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        if ((state_load_reg_699_pp0_iter38_reg == 2'd3)) begin
            seven_segment_enable = 4'd14;
        end else if ((state_load_reg_699_pp0_iter38_reg == 2'd0)) begin
            seven_segment_enable = 4'd7;
        end else if ((state_load_reg_699_pp0_iter38_reg == 2'd1)) begin
            seven_segment_enable = 4'd11;
        end else if ((state_load_reg_699_pp0_iter38_reg == 2'd2)) begin
            seven_segment_enable = 4'd13;
        end else begin
            seven_segment_enable = 'bx;
        end
    end else begin
        seven_segment_enable = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_1_fu_451_p2 = ($signed(zext_ln317_1_fu_447_p1) + $signed(9'd385));

assign add_ln317_2_fu_581_p2 = ($signed(zext_ln317_2_fu_578_p1) + $signed(9'd385));

assign add_ln317_fu_250_p2 = ($signed(zext_ln317_fu_246_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_next_state_4_reg_172 = 'bx;

assign data_1_fu_430_p1 = dc_reg_730;

assign data_2_fu_542_p1 = grp_fu_198_p2;

assign data_fu_214_p1 = acc;

assign grp_fu_203_p0 = ((tmp_2_reg_684[0:0] == 1'b1) ? tmp_reg_689 : tmp_1_reg_694);

assign grp_fu_209_p0 = grp_fu_209_p00;

assign grp_fu_209_p00 = val_reg_703;

assign grp_fu_209_p1 = 65'd6871947674;

assign grp_fu_406_p1 = 32'd10;

assign grp_fu_425_p1 = 29'd10;

assign lshr_ln71_1_fu_503_p2 = zext_ln68_1_fu_492_p1 >> zext_ln71_1_fu_499_p1;

assign lshr_ln71_2_fu_620_p2 = zext_ln68_2_fu_574_p1 >> zext_ln71_2_fu_616_p1;

assign lshr_ln71_fu_290_p2 = zext_ln68_fu_242_p1 >> zext_ln71_fu_286_p1;

assign mantissa_1_fu_483_p4 = {{{{1'd1}, {trunc_ln342_1_reg_736}}}, {1'd0}};

assign mantissa_2_fu_565_p4 = {{{{1'd1}, {trunc_ln342_2_reg_777}}}, {1'd0}};

assign mantissa_fu_232_p4 = {{{{1'd1}, {trunc_ln342_fu_228_p1}}}, {1'd0}};

assign next_state_1_fu_368_p2 = (next_state_fu_330_p2 ^ 1'd1);

assign next_state_2_fu_359_p3 = ((next_state_fu_330_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign next_state_3_fu_350_p3 = ((next_state_fu_330_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign next_state_fu_330_p2 = ((timer != 32'd0) ? 1'b1 : 1'b0);

assign next_timer_1_fu_342_p3 = ((next_state_fu_330_p2[0:0] == 1'b1) ? next_timer_fu_336_p2 : 32'd100000);

assign next_timer_fu_336_p2 = ($signed(timer) + $signed(32'd4294967295));

assign select_ln71_2_fu_475_p3 = ((tmp_3_fu_457_p3[0:0] == 1'b1) ? sext_ln71_2_fu_471_p1 : add_ln317_1_fu_451_p2);

assign select_ln71_3_fu_515_p3 = ((tmp_3_reg_741[0:0] == 1'b1) ? lshr_ln71_1_fu_503_p2 : shl_ln71_1_fu_509_p2);

assign select_ln71_4_fu_604_p3 = ((tmp_6_fu_587_p3[0:0] == 1'b1) ? sext_ln71_4_fu_600_p1 : add_ln317_2_fu_581_p2);

assign select_ln71_5_fu_657_p3 = ((tmp_6_reg_787[0:0] == 1'b1) ? tmp_4_reg_792 : tmp_5_reg_797);

assign select_ln71_fu_274_p3 = ((tmp_2_fu_256_p3[0:0] == 1'b1) ? sext_ln71_fu_270_p1 : add_ln317_fu_250_p2);

assign select_ln74_1_fu_379_p3 = ((next_state_fu_330_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign seven_segment_code_address1 = zext_ln42_fu_652_p1;

assign seven_segment_code_address2 = zext_ln27_fu_560_p1;

assign sext_ln71_1_fu_282_p1 = $signed(select_ln71_fu_274_p3);

assign sext_ln71_2_fu_471_p1 = $signed(sub_ln71_1_fu_465_p2);

assign sext_ln71_3_fu_496_p1 = $signed(select_ln71_2_reg_746);

assign sext_ln71_4_fu_600_p1 = $signed(sub_ln71_2_fu_595_p2);

assign sext_ln71_5_fu_612_p1 = $signed(select_ln71_4_fu_604_p3);

assign sext_ln71_fu_270_p1 = $signed(sub_ln71_fu_264_p2);

assign shl_ln71_1_fu_509_p2 = zext_ln68_1_fu_492_p1 << zext_ln71_1_fu_499_p1;

assign shl_ln71_2_fu_626_p2 = zext_ln68_2_fu_574_p1 << zext_ln71_2_fu_616_p1;

assign shl_ln71_fu_296_p2 = zext_ln68_fu_242_p1 << zext_ln71_fu_286_p1;

assign state_load_load_fu_322_p1 = state;

assign sub_ln71_1_fu_465_p2 = (8'd127 - xs_exp_1_fu_433_p4);

assign sub_ln71_2_fu_595_p2 = (8'd127 - xs_exp_2_reg_771);

assign sub_ln71_fu_264_p2 = (8'd127 - xs_exp_fu_218_p4);

assign tmp_2_fu_256_p3 = add_ln317_fu_250_p2[32'd8];

assign tmp_3_fu_457_p3 = add_ln317_1_fu_451_p2[32'd8];

assign tmp_6_fu_587_p3 = add_ln317_2_fu_581_p2[32'd8];

assign trunc_ln342_1_fu_443_p1 = data_1_fu_430_p1[22:0];

assign trunc_ln342_2_fu_556_p1 = data_2_fu_542_p1[22:0];

assign trunc_ln342_fu_228_p1 = data_fu_214_p1[22:0];

assign trunc_ln42_fu_666_p1 = seven_segment_code_q1[6:0];

assign val_fu_400_p3 = ((tmp_2_reg_684[0:0] == 1'b1) ? tmp_reg_689 : tmp_1_reg_694);

assign xs_exp_1_fu_433_p4 = {{data_1_fu_430_p1[30:23]}};

assign xs_exp_fu_218_p4 = {{data_fu_214_p1[30:23]}};

assign zext_ln21_fu_374_p1 = next_state_1_fu_368_p2;

assign zext_ln27_fu_560_p1 = grp_fu_425_p2;

assign zext_ln317_1_fu_447_p1 = xs_exp_1_fu_433_p4;

assign zext_ln317_2_fu_578_p1 = xs_exp_2_reg_771;

assign zext_ln317_fu_246_p1 = xs_exp_fu_218_p4;

assign zext_ln42_1_fu_675_p1 = trunc_ln42_reg_817;

assign zext_ln42_fu_652_p1 = grp_fu_406_p2;

assign zext_ln57_fu_662_p1 = c_reg_756_pp0_iter37_reg;

assign zext_ln68_1_fu_492_p1 = mantissa_1_fu_483_p4;

assign zext_ln68_2_fu_574_p1 = mantissa_2_fu_565_p4;

assign zext_ln68_fu_242_p1 = mantissa_fu_232_p4;

assign zext_ln71_1_fu_499_p1 = $unsigned(sext_ln71_3_fu_496_p1);

assign zext_ln71_2_fu_616_p1 = $unsigned(sext_ln71_5_fu_612_p1);

assign zext_ln71_fu_286_p1 = $unsigned(sext_ln71_1_fu_282_p1);

assign zext_ln72_fu_670_p1 = select_ln71_5_fu_657_p3;

endmodule //display_float
