// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dice_roller_lfsr_dice_roller_lfsr,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.745000,HLS_SYN_LAT=37,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2430,HLS_SYN_LUT=1804,HLS_VERSION=2023_2}" *)

module dice_roller_lfsr (
        ap_clk,
        ap_rst,
        roll,
        seven_segment_data,
        seven_segment_enable
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [0:0] roll;
output  [7:0] seven_segment_data;
output  [3:0] seven_segment_enable;

reg   [0:0] first_time;
reg   [31:0] lfsr;
reg   [2:0] rand_number;
wire   [3:0] seven_segment_code_numbers_address0;
reg    seven_segment_code_numbers_ce0;
wire   [7:0] seven_segment_code_numbers_q0;
wire   [0:0] roll_read_read_fu_66_p2;
reg   [0:0] roll_read_reg_227;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] roll_read_reg_227_pp0_iter1_reg;
reg   [0:0] roll_read_reg_227_pp0_iter2_reg;
reg   [0:0] roll_read_reg_227_pp0_iter3_reg;
reg   [0:0] roll_read_reg_227_pp0_iter4_reg;
reg   [0:0] roll_read_reg_227_pp0_iter5_reg;
reg   [0:0] roll_read_reg_227_pp0_iter6_reg;
reg   [0:0] roll_read_reg_227_pp0_iter7_reg;
reg   [0:0] roll_read_reg_227_pp0_iter8_reg;
reg   [0:0] roll_read_reg_227_pp0_iter9_reg;
reg   [0:0] roll_read_reg_227_pp0_iter10_reg;
reg   [0:0] roll_read_reg_227_pp0_iter11_reg;
reg   [0:0] roll_read_reg_227_pp0_iter12_reg;
reg   [0:0] roll_read_reg_227_pp0_iter13_reg;
reg   [0:0] roll_read_reg_227_pp0_iter14_reg;
reg   [0:0] roll_read_reg_227_pp0_iter15_reg;
reg   [0:0] roll_read_reg_227_pp0_iter16_reg;
reg   [0:0] roll_read_reg_227_pp0_iter17_reg;
reg   [0:0] roll_read_reg_227_pp0_iter18_reg;
reg   [0:0] roll_read_reg_227_pp0_iter19_reg;
reg   [0:0] roll_read_reg_227_pp0_iter20_reg;
reg   [0:0] roll_read_reg_227_pp0_iter21_reg;
reg   [0:0] roll_read_reg_227_pp0_iter22_reg;
reg   [0:0] roll_read_reg_227_pp0_iter23_reg;
reg   [0:0] roll_read_reg_227_pp0_iter24_reg;
reg   [0:0] roll_read_reg_227_pp0_iter25_reg;
reg   [0:0] roll_read_reg_227_pp0_iter26_reg;
reg   [0:0] roll_read_reg_227_pp0_iter27_reg;
reg   [0:0] roll_read_reg_227_pp0_iter28_reg;
reg   [0:0] roll_read_reg_227_pp0_iter29_reg;
reg   [0:0] roll_read_reg_227_pp0_iter30_reg;
reg   [0:0] roll_read_reg_227_pp0_iter31_reg;
reg   [0:0] roll_read_reg_227_pp0_iter32_reg;
reg   [0:0] roll_read_reg_227_pp0_iter33_reg;
reg   [0:0] roll_read_reg_227_pp0_iter34_reg;
wire   [31:0] tmp_fu_182_p3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg   [31:0] ap_phi_mux_lfsr_loc_0_phi_fu_104_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_lfsr_loc_0_reg_101;
wire   [0:0] first_time_load_load_fu_111_p1;
wire   [63:0] zext_ln56_fu_222_p1;
wire    ap_block_pp0_stage0;
wire   [2:0] r_fu_206_p2;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln16_fu_126_p1;
wire   [0:0] tmp_2_fu_138_p3;
wire   [0:0] xor_ln16_fu_146_p2;
wire   [0:0] tmp_1_fu_130_p3;
wire   [0:0] xor_ln16_1_fu_152_p2;
wire   [0:0] tmp_3_fu_158_p3;
wire   [0:0] new_bit_fu_166_p2;
wire   [30:0] lshr_ln_fu_172_p4;
wire   [31:0] grp_fu_190_p0;
wire   [3:0] grp_fu_190_p1;
wire   [2:0] grp_fu_190_p2;
wire   [2:0] trunc_ln36_fu_202_p1;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 first_time = 1'd1;
#0 lfsr = 32'd0;
#0 rand_number = 3'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
end

dice_roller_lfsr_seven_segment_code_numbers_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
seven_segment_code_numbers_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(seven_segment_code_numbers_address0),
    .ce0(seven_segment_code_numbers_ce0),
    .q0(seven_segment_code_numbers_q0)
);

dice_roller_lfsr_urem_32ns_4ns_3_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_32ns_4ns_3_36_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_190_p0),
    .din1(grp_fu_190_p1),
    .ce(1'b1),
    .dout(grp_fu_190_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (roll_read_read_fu_66_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_time_load_load_fu_111_p1 == 1'd1) & (1'b1 == 1'b1))) begin
        first_time <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (roll_read_read_fu_66_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1))) begin
        lfsr <= tmp_fu_182_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((roll_read_reg_227_pp0_iter34_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        rand_number <= r_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        roll_read_reg_227 <= roll;
        roll_read_reg_227_pp0_iter1_reg <= roll_read_reg_227;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        roll_read_reg_227_pp0_iter10_reg <= roll_read_reg_227_pp0_iter9_reg;
        roll_read_reg_227_pp0_iter11_reg <= roll_read_reg_227_pp0_iter10_reg;
        roll_read_reg_227_pp0_iter12_reg <= roll_read_reg_227_pp0_iter11_reg;
        roll_read_reg_227_pp0_iter13_reg <= roll_read_reg_227_pp0_iter12_reg;
        roll_read_reg_227_pp0_iter14_reg <= roll_read_reg_227_pp0_iter13_reg;
        roll_read_reg_227_pp0_iter15_reg <= roll_read_reg_227_pp0_iter14_reg;
        roll_read_reg_227_pp0_iter16_reg <= roll_read_reg_227_pp0_iter15_reg;
        roll_read_reg_227_pp0_iter17_reg <= roll_read_reg_227_pp0_iter16_reg;
        roll_read_reg_227_pp0_iter18_reg <= roll_read_reg_227_pp0_iter17_reg;
        roll_read_reg_227_pp0_iter19_reg <= roll_read_reg_227_pp0_iter18_reg;
        roll_read_reg_227_pp0_iter20_reg <= roll_read_reg_227_pp0_iter19_reg;
        roll_read_reg_227_pp0_iter21_reg <= roll_read_reg_227_pp0_iter20_reg;
        roll_read_reg_227_pp0_iter22_reg <= roll_read_reg_227_pp0_iter21_reg;
        roll_read_reg_227_pp0_iter23_reg <= roll_read_reg_227_pp0_iter22_reg;
        roll_read_reg_227_pp0_iter24_reg <= roll_read_reg_227_pp0_iter23_reg;
        roll_read_reg_227_pp0_iter25_reg <= roll_read_reg_227_pp0_iter24_reg;
        roll_read_reg_227_pp0_iter26_reg <= roll_read_reg_227_pp0_iter25_reg;
        roll_read_reg_227_pp0_iter27_reg <= roll_read_reg_227_pp0_iter26_reg;
        roll_read_reg_227_pp0_iter28_reg <= roll_read_reg_227_pp0_iter27_reg;
        roll_read_reg_227_pp0_iter29_reg <= roll_read_reg_227_pp0_iter28_reg;
        roll_read_reg_227_pp0_iter2_reg <= roll_read_reg_227_pp0_iter1_reg;
        roll_read_reg_227_pp0_iter30_reg <= roll_read_reg_227_pp0_iter29_reg;
        roll_read_reg_227_pp0_iter31_reg <= roll_read_reg_227_pp0_iter30_reg;
        roll_read_reg_227_pp0_iter32_reg <= roll_read_reg_227_pp0_iter31_reg;
        roll_read_reg_227_pp0_iter33_reg <= roll_read_reg_227_pp0_iter32_reg;
        roll_read_reg_227_pp0_iter34_reg <= roll_read_reg_227_pp0_iter33_reg;
        roll_read_reg_227_pp0_iter3_reg <= roll_read_reg_227_pp0_iter2_reg;
        roll_read_reg_227_pp0_iter4_reg <= roll_read_reg_227_pp0_iter3_reg;
        roll_read_reg_227_pp0_iter5_reg <= roll_read_reg_227_pp0_iter4_reg;
        roll_read_reg_227_pp0_iter6_reg <= roll_read_reg_227_pp0_iter5_reg;
        roll_read_reg_227_pp0_iter7_reg <= roll_read_reg_227_pp0_iter6_reg;
        roll_read_reg_227_pp0_iter8_reg <= roll_read_reg_227_pp0_iter7_reg;
        roll_read_reg_227_pp0_iter9_reg <= roll_read_reg_227_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 
    == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((roll_read_read_fu_66_p2 == 1'd1)) begin
        if ((first_time_load_load_fu_111_p1 == 1'd0)) begin
            ap_phi_mux_lfsr_loc_0_phi_fu_104_p4 = lfsr;
        end else if ((first_time_load_load_fu_111_p1 == 1'd1)) begin
            ap_phi_mux_lfsr_loc_0_phi_fu_104_p4 = 32'd2147483653;
        end else begin
            ap_phi_mux_lfsr_loc_0_phi_fu_104_p4 = ap_phi_reg_pp0_iter0_lfsr_loc_0_reg_101;
        end
    end else begin
        ap_phi_mux_lfsr_loc_0_phi_fu_104_p4 = ap_phi_reg_pp0_iter0_lfsr_loc_0_reg_101;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        seven_segment_code_numbers_ce0 = 1'b1;
    end else begin
        seven_segment_code_numbers_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_lfsr_loc_0_reg_101 = 'bx;

assign first_time_load_load_fu_111_p1 = first_time;

assign grp_fu_190_p0 = {{new_bit_fu_166_p2}, {lshr_ln_fu_172_p4}};

assign grp_fu_190_p1 = 32'd6;

assign lshr_ln_fu_172_p4 = {{ap_phi_mux_lfsr_loc_0_phi_fu_104_p4[31:1]}};

assign new_bit_fu_166_p2 = (xor_ln16_1_fu_152_p2 ^ tmp_3_fu_158_p3);

assign r_fu_206_p2 = (trunc_ln36_fu_202_p1 + 3'd1);

assign roll_read_read_fu_66_p2 = roll;

assign seven_segment_code_numbers_address0 = zext_ln56_fu_222_p1;

assign seven_segment_data = seven_segment_code_numbers_q0;

assign seven_segment_enable = 4'd14;

assign tmp_1_fu_130_p3 = ap_phi_mux_lfsr_loc_0_phi_fu_104_p4[32'd10];

assign tmp_2_fu_138_p3 = ap_phi_mux_lfsr_loc_0_phi_fu_104_p4[32'd30];

assign tmp_3_fu_158_p3 = ap_phi_mux_lfsr_loc_0_phi_fu_104_p4[32'd31];

assign tmp_fu_182_p3 = {{new_bit_fu_166_p2}, {lshr_ln_fu_172_p4}};

assign trunc_ln16_fu_126_p1 = ap_phi_mux_lfsr_loc_0_phi_fu_104_p4[0:0];

assign trunc_ln36_fu_202_p1 = grp_fu_190_p2[2:0];

assign xor_ln16_1_fu_152_p2 = (xor_ln16_fu_146_p2 ^ tmp_1_fu_130_p3);

assign xor_ln16_fu_146_p2 = (trunc_ln16_fu_126_p1 ^ tmp_2_fu_138_p3);

assign zext_ln56_fu_222_p1 = rand_number;

endmodule //dice_roller_lfsr
