-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity four_digit_counter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    counter_init_value : IN STD_LOGIC_VECTOR (13 downto 0);
    load : IN STD_LOGIC_VECTOR (0 downto 0);
    up_count : IN STD_LOGIC_VECTOR (0 downto 0);
    down_count : IN STD_LOGIC_VECTOR (0 downto 0);
    first_digit : OUT STD_LOGIC_VECTOR (3 downto 0);
    second_digit : OUT STD_LOGIC_VECTOR (3 downto 0);
    third_digit : OUT STD_LOGIC_VECTOR (3 downto 0);
    fourth_digit : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of four_digit_counter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "four_digit_counter_four_digit_counter,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.023917,HLS_SYN_LAT=17,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1266,HLS_SYN_LUT=1025,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv14_270F : STD_LOGIC_VECTOR (13 downto 0) := "10011100001111";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv14_A : STD_LOGIC_VECTOR (13 downto 0) := "00000000001010";
    constant ap_const_lv29_6667 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000110011001100111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv29_51EC : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000101000111101100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv29_418A : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000100000110001010";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv11_A : STD_LOGIC_VECTOR (10 downto 0) := "00000001010";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";

    signal counter : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal next_counter_3_fu_198_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal next_counter_3_reg_319 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln1_reg_325 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln60_1_reg_330 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln60_2_reg_335 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln60_2_cast_reg_340 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_fu_299_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln70_reg_346_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_284_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal urem_ln67_reg_351 : STD_LOGIC_VECTOR (3 downto 0);
    signal urem_ln67_reg_351_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal urem_ln67_reg_351_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal urem_ln67_reg_351_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal urem_ln64_reg_356 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln36_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln42_fu_156_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln36_fu_162_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal next_counter_fu_142_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln48_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln54_fu_184_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln48_fu_190_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal next_counter_1_fu_170_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_206_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_206_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln62_fu_221_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln62_fu_218_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln62_fu_221_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln62_fu_221_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln65_fu_237_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln65_fu_237_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln65_fu_237_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln68_fu_253_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln68_fu_253_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln68_fu_253_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_279_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_284_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln70_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln70_fu_294_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_206_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component four_digit_counter_urem_14ns_5ns_4_18_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component four_digit_counter_mul_14ns_16ns_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component four_digit_counter_urem_11ns_5ns_4_15_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component four_digit_counter_urem_8ns_5ns_4_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    urem_14ns_5ns_4_18_1_U1 : component four_digit_counter_urem_14ns_5ns_4_18_1
    generic map (
        ID => 1,
        NUM_STAGE => 18,
        din0_WIDTH => 14,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_206_p0,
        din1 => grp_fu_206_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_206_p2);

    mul_14ns_16ns_29_1_1_U2 : component four_digit_counter_mul_14ns_16ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln62_fu_221_p0,
        din1 => mul_ln62_fu_221_p1,
        dout => mul_ln62_fu_221_p2);

    mul_14ns_16ns_29_1_1_U3 : component four_digit_counter_mul_14ns_16ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln65_fu_237_p0,
        din1 => mul_ln65_fu_237_p1,
        dout => mul_ln65_fu_237_p2);

    mul_14ns_16ns_29_1_1_U4 : component four_digit_counter_mul_14ns_16ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 16,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln68_fu_253_p0,
        din1 => mul_ln68_fu_253_p1,
        dout => mul_ln68_fu_253_p2);

    urem_11ns_5ns_4_15_1_U5 : component four_digit_counter_urem_11ns_5ns_4_15_1
    generic map (
        ID => 1,
        NUM_STAGE => 15,
        din0_WIDTH => 11,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln1_reg_325,
        din1 => grp_fu_279_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_279_p2);

    urem_8ns_5ns_4_12_1_U6 : component four_digit_counter_urem_8ns_5ns_4_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln60_1_reg_330,
        din1 => grp_fu_284_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_284_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then
                counter <= next_counter_3_fu_198_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                next_counter_3_reg_319 <= next_counter_3_fu_198_p3;
                trunc_ln1_reg_325 <= mul_ln62_fu_221_p2(28 downto 18);
                trunc_ln60_1_reg_330 <= mul_ln65_fu_237_p2(28 downto 21);
                trunc_ln60_2_cast_reg_340 <= mul_ln68_fu_253_p2(27 downto 24);
                trunc_ln60_2_reg_335 <= mul_ln68_fu_253_p2(28 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                select_ln70_reg_346 <= select_ln70_fu_299_p3;
                select_ln70_reg_346_pp0_iter10_reg <= select_ln70_reg_346_pp0_iter9_reg;
                select_ln70_reg_346_pp0_iter11_reg <= select_ln70_reg_346_pp0_iter10_reg;
                select_ln70_reg_346_pp0_iter12_reg <= select_ln70_reg_346_pp0_iter11_reg;
                select_ln70_reg_346_pp0_iter13_reg <= select_ln70_reg_346_pp0_iter12_reg;
                select_ln70_reg_346_pp0_iter14_reg <= select_ln70_reg_346_pp0_iter13_reg;
                select_ln70_reg_346_pp0_iter15_reg <= select_ln70_reg_346_pp0_iter14_reg;
                select_ln70_reg_346_pp0_iter16_reg <= select_ln70_reg_346_pp0_iter15_reg;
                select_ln70_reg_346_pp0_iter3_reg <= select_ln70_reg_346;
                select_ln70_reg_346_pp0_iter4_reg <= select_ln70_reg_346_pp0_iter3_reg;
                select_ln70_reg_346_pp0_iter5_reg <= select_ln70_reg_346_pp0_iter4_reg;
                select_ln70_reg_346_pp0_iter6_reg <= select_ln70_reg_346_pp0_iter5_reg;
                select_ln70_reg_346_pp0_iter7_reg <= select_ln70_reg_346_pp0_iter6_reg;
                select_ln70_reg_346_pp0_iter8_reg <= select_ln70_reg_346_pp0_iter7_reg;
                select_ln70_reg_346_pp0_iter9_reg <= select_ln70_reg_346_pp0_iter8_reg;
                urem_ln64_reg_356 <= grp_fu_279_p2;
                urem_ln67_reg_351 <= grp_fu_284_p2;
                urem_ln67_reg_351_pp0_iter14_reg <= urem_ln67_reg_351;
                urem_ln67_reg_351_pp0_iter15_reg <= urem_ln67_reg_351_pp0_iter14_reg;
                urem_ln67_reg_351_pp0_iter16_reg <= urem_ln67_reg_351_pp0_iter15_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln42_fu_156_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv14_1));
    add_ln54_fu_184_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv14_3FFF));
    add_ln70_fu_294_p2 <= std_logic_vector(unsigned(trunc_ln60_2_cast_reg_340) + unsigned(ap_const_lv4_6));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;
    first_digit <= grp_fu_206_p2(4 - 1 downto 0);
    fourth_digit <= select_ln70_reg_346_pp0_iter16_reg;
    grp_fu_206_p0 <= 
        select_ln48_fu_190_p3 when (down_count(0) = '1') else 
        next_counter_1_fu_170_p3;
    grp_fu_206_p1 <= ap_const_lv14_A(5 - 1 downto 0);
    grp_fu_279_p1 <= ap_const_lv11_A(5 - 1 downto 0);
    grp_fu_284_p1 <= ap_const_lv8_A(5 - 1 downto 0);
    icmp_ln36_fu_150_p2 <= "1" when (counter = ap_const_lv14_270F) else "0";
    icmp_ln48_fu_178_p2 <= "1" when (counter = ap_const_lv14_0) else "0";
    icmp_ln70_fu_289_p2 <= "1" when (unsigned(trunc_ln60_2_reg_335) < unsigned(ap_const_lv5_A)) else "0";
    mul_ln62_fu_221_p0 <= zext_ln62_fu_218_p1(14 - 1 downto 0);
    mul_ln62_fu_221_p1 <= ap_const_lv29_6667(16 - 1 downto 0);
    mul_ln65_fu_237_p0 <= zext_ln62_fu_218_p1(14 - 1 downto 0);
    mul_ln65_fu_237_p1 <= ap_const_lv29_51EC(16 - 1 downto 0);
    mul_ln68_fu_253_p0 <= zext_ln62_fu_218_p1(14 - 1 downto 0);
    mul_ln68_fu_253_p1 <= ap_const_lv29_418A(16 - 1 downto 0);
    next_counter_1_fu_170_p3 <= 
        select_ln36_fu_162_p3 when (up_count(0) = '1') else 
        next_counter_fu_142_p3;
    next_counter_3_fu_198_p3 <= 
        select_ln48_fu_190_p3 when (down_count(0) = '1') else 
        next_counter_1_fu_170_p3;
    next_counter_fu_142_p3 <= 
        counter_init_value when (load(0) = '1') else 
        counter;
    second_digit <= urem_ln64_reg_356(4 - 1 downto 0);
    select_ln36_fu_162_p3 <= 
        ap_const_lv14_0 when (icmp_ln36_fu_150_p2(0) = '1') else 
        add_ln42_fu_156_p2;
    select_ln48_fu_190_p3 <= 
        ap_const_lv14_270F when (icmp_ln48_fu_178_p2(0) = '1') else 
        add_ln54_fu_184_p2;
    select_ln70_fu_299_p3 <= 
        trunc_ln60_2_cast_reg_340 when (icmp_ln70_fu_289_p2(0) = '1') else 
        add_ln70_fu_294_p2;
    third_digit <= urem_ln67_reg_351_pp0_iter16_reg(4 - 1 downto 0);
    zext_ln62_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(next_counter_3_reg_319),29));
end behav;
