-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity seven_segment_driver_new is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    refresh_signal : IN STD_LOGIC_VECTOR (0 downto 0);
    first_digit : IN STD_LOGIC_VECTOR (3 downto 0);
    second_digit : IN STD_LOGIC_VECTOR (3 downto 0);
    third_digit : IN STD_LOGIC_VECTOR (3 downto 0);
    fourth_digit : IN STD_LOGIC_VECTOR (3 downto 0);
    seven_segment_data : OUT STD_LOGIC_VECTOR (7 downto 0);
    seven_segment_enable : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of seven_segment_driver_new is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "seven_segment_driver_new_seven_segment_driver_new,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.532000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=23,HLS_SYN_LUT=125,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";

    signal state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal seven_segment_code_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_ce0 : STD_LOGIC;
    signal seven_segment_code_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln33_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln33_reg_365_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_1_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_1_reg_370 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_1_reg_370_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_2_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_2_reg_375 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_2_reg_375_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_6_fu_272_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln7_6_reg_381 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal zext_ln7_fu_334_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal next_state_fu_320_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln33_3_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln7_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_6_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_5_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_4_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_3_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_2_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_1_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln7_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_fu_200_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln7_1_fu_214_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln7_1_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_2_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_2_fu_228_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln7_3_fu_242_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln7_3_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_4_fu_250_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln7_5_fu_264_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln7_5_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_4_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_7_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_6_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_7_fu_292_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln7_8_fu_312_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln33_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln33_fu_338_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln33_1_fu_349_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component seven_segment_driver_new_seven_segment_code_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    seven_segment_code_U : component seven_segment_driver_new_seven_segment_code_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => seven_segment_code_address0,
        ce0 => seven_segment_code_ce0,
        q0 => seven_segment_code_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln33_1_reg_370 <= icmp_ln33_1_fu_140_p2;
                icmp_ln33_1_reg_370_pp0_iter1_reg <= icmp_ln33_1_reg_370;
                icmp_ln33_2_reg_375 <= icmp_ln33_2_fu_152_p2;
                icmp_ln33_2_reg_375_pp0_iter1_reg <= icmp_ln33_2_reg_375;
                icmp_ln33_reg_365 <= icmp_ln33_fu_128_p2;
                icmp_ln33_reg_365_pp0_iter1_reg <= icmp_ln33_reg_365;
                select_ln7_6_reg_381 <= select_ln7_6_fu_272_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                state <= next_state_fu_320_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln7_1_fu_146_p2 <= (refresh_signal and icmp_ln33_1_fu_140_p2);
    and_ln7_2_fu_158_p2 <= (refresh_signal and icmp_ln33_2_fu_152_p2);
    and_ln7_3_fu_176_p2 <= (xor_ln7_fu_170_p2 and icmp_ln33_3_fu_164_p2);
    and_ln7_4_fu_182_p2 <= (xor_ln7_fu_170_p2 and icmp_ln33_fu_128_p2);
    and_ln7_5_fu_188_p2 <= (xor_ln7_fu_170_p2 and icmp_ln33_1_fu_140_p2);
    and_ln7_6_fu_194_p2 <= (xor_ln7_fu_170_p2 and icmp_ln33_2_fu_152_p2);
    and_ln7_fu_134_p2 <= (refresh_signal and icmp_ln33_fu_128_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;
    icmp_ln33_1_fu_140_p2 <= "1" when (state = ap_const_lv2_1) else "0";
    icmp_ln33_2_fu_152_p2 <= "1" when (state = ap_const_lv2_0) else "0";
    icmp_ln33_3_fu_164_p2 <= "1" when (state = ap_const_lv2_3) else "0";
    icmp_ln33_fu_128_p2 <= "1" when (state = ap_const_lv2_2) else "0";
    next_state_fu_320_p3 <= 
        select_ln7_7_fu_292_p3 when (or_ln7_6_fu_300_p2(0) = '1') else 
        select_ln7_8_fu_312_p3;
    or_ln33_fu_345_p2 <= (icmp_ln33_2_reg_375_pp0_iter1_reg or icmp_ln33_1_reg_370_pp0_iter1_reg);
    or_ln7_1_fu_222_p2 <= (and_ln7_4_fu_182_p2 or and_ln7_3_fu_176_p2);
    or_ln7_2_fu_236_p2 <= (and_ln7_2_fu_158_p2 or and_ln7_1_fu_146_p2);
    or_ln7_3_fu_258_p2 <= (or_ln7_fu_208_p2 or or_ln7_1_fu_222_p2);
    or_ln7_4_fu_280_p2 <= (and_ln7_4_fu_182_p2 or and_ln7_1_fu_146_p2);
    or_ln7_5_fu_286_p2 <= (and_ln7_5_fu_188_p2 or and_ln7_2_fu_158_p2);
    or_ln7_6_fu_300_p2 <= (or_ln7_5_fu_286_p2 or or_ln7_4_fu_280_p2);
    or_ln7_7_fu_306_p2 <= (and_ln7_fu_134_p2 or and_ln7_3_fu_176_p2);
    or_ln7_fu_208_p2 <= (and_ln7_6_fu_194_p2 or and_ln7_5_fu_188_p2);
    select_ln33_1_fu_349_p3 <= 
        ap_const_lv4_B when (icmp_ln33_reg_365_pp0_iter1_reg(0) = '1') else 
        ap_const_lv4_7;
    select_ln33_fu_338_p3 <= 
        ap_const_lv4_E when (icmp_ln33_2_reg_375_pp0_iter1_reg(0) = '1') else 
        ap_const_lv4_D;
    select_ln7_1_fu_214_p3 <= 
        third_digit when (and_ln7_4_fu_182_p2(0) = '1') else 
        fourth_digit;
    select_ln7_2_fu_228_p3 <= 
        second_digit when (and_ln7_2_fu_158_p2(0) = '1') else 
        third_digit;
    select_ln7_3_fu_242_p3 <= 
        fourth_digit when (and_ln7_fu_134_p2(0) = '1') else 
        first_digit;
    select_ln7_4_fu_250_p3 <= 
        select_ln7_fu_200_p3 when (or_ln7_fu_208_p2(0) = '1') else 
        select_ln7_1_fu_214_p3;
    select_ln7_5_fu_264_p3 <= 
        select_ln7_2_fu_228_p3 when (or_ln7_2_fu_236_p2(0) = '1') else 
        select_ln7_3_fu_242_p3;
    select_ln7_6_fu_272_p3 <= 
        select_ln7_4_fu_250_p3 when (or_ln7_3_fu_258_p2(0) = '1') else 
        select_ln7_5_fu_264_p3;
    select_ln7_7_fu_292_p3 <= 
        ap_const_lv2_1 when (or_ln7_5_fu_286_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln7_8_fu_312_p3 <= 
        ap_const_lv2_3 when (or_ln7_7_fu_306_p2(0) = '1') else 
        ap_const_lv2_0;
    select_ln7_fu_200_p3 <= 
        first_digit when (and_ln7_6_fu_194_p2(0) = '1') else 
        second_digit;
    seven_segment_code_address0 <= zext_ln7_fu_334_p1(4 - 1 downto 0);

    seven_segment_code_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            seven_segment_code_ce0 <= ap_const_logic_1;
        else 
            seven_segment_code_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    seven_segment_data <= seven_segment_code_q0;
    seven_segment_enable <= 
        select_ln33_fu_338_p3 when (or_ln33_fu_345_p2(0) = '1') else 
        select_ln33_1_fu_349_p3;
    xor_ln7_fu_170_p2 <= (refresh_signal xor ap_const_lv1_1);
    zext_ln7_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln7_6_reg_381),64));
end behav;
