// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="four_digit_counter_four_digit_counter,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.023917,HLS_SYN_LAT=17,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1266,HLS_SYN_LUT=1025,HLS_VERSION=2023_2}" *)

module four_digit_counter (
        ap_clk,
        ap_rst,
        counter_init_value,
        load,
        up_count,
        down_count,
        first_digit,
        second_digit,
        third_digit,
        fourth_digit
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [13:0] counter_init_value;
input  [0:0] load;
input  [0:0] up_count;
input  [0:0] down_count;
output  [3:0] first_digit;
output  [3:0] second_digit;
output  [3:0] third_digit;
output  [3:0] fourth_digit;

reg   [13:0] counter;
wire   [13:0] next_counter_3_fu_198_p3;
reg   [13:0] next_counter_3_reg_319;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [10:0] trunc_ln1_reg_325;
reg   [7:0] trunc_ln60_1_reg_330;
reg   [4:0] trunc_ln60_2_reg_335;
reg   [3:0] trunc_ln60_2_cast_reg_340;
wire   [3:0] select_ln70_fu_299_p3;
reg   [3:0] select_ln70_reg_346;
reg   [3:0] select_ln70_reg_346_pp0_iter3_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter4_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter5_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter6_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter7_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter8_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter9_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter10_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter11_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter12_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter13_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter14_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter15_reg;
reg   [3:0] select_ln70_reg_346_pp0_iter16_reg;
wire   [3:0] grp_fu_284_p2;
reg   [3:0] urem_ln67_reg_351;
reg   [3:0] urem_ln67_reg_351_pp0_iter14_reg;
reg   [3:0] urem_ln67_reg_351_pp0_iter15_reg;
reg   [3:0] urem_ln67_reg_351_pp0_iter16_reg;
wire   [3:0] grp_fu_279_p2;
reg   [3:0] urem_ln64_reg_356;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln36_fu_150_p2;
wire   [13:0] add_ln42_fu_156_p2;
wire   [13:0] select_ln36_fu_162_p3;
wire   [13:0] next_counter_fu_142_p3;
wire   [0:0] icmp_ln48_fu_178_p2;
wire   [13:0] add_ln54_fu_184_p2;
wire   [13:0] select_ln48_fu_190_p3;
wire   [13:0] next_counter_1_fu_170_p3;
wire   [13:0] grp_fu_206_p0;
wire   [4:0] grp_fu_206_p1;
wire   [13:0] mul_ln62_fu_221_p0;
wire   [28:0] zext_ln62_fu_218_p1;
wire   [15:0] mul_ln62_fu_221_p1;
wire   [28:0] mul_ln62_fu_221_p2;
wire   [13:0] mul_ln65_fu_237_p0;
wire   [15:0] mul_ln65_fu_237_p1;
wire   [28:0] mul_ln65_fu_237_p2;
wire   [13:0] mul_ln68_fu_253_p0;
wire   [15:0] mul_ln68_fu_253_p1;
wire   [28:0] mul_ln68_fu_253_p2;
wire   [4:0] grp_fu_279_p1;
wire   [4:0] grp_fu_284_p1;
wire   [0:0] icmp_ln70_fu_289_p2;
wire   [3:0] add_ln70_fu_294_p2;
wire   [3:0] grp_fu_206_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 counter = 14'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
end

four_digit_counter_urem_14ns_5ns_4_18_1 #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_14ns_5ns_4_18_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_206_p0),
    .din1(grp_fu_206_p1),
    .ce(1'b1),
    .dout(grp_fu_206_p2)
);

four_digit_counter_mul_14ns_16ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_14ns_16ns_29_1_1_U2(
    .din0(mul_ln62_fu_221_p0),
    .din1(mul_ln62_fu_221_p1),
    .dout(mul_ln62_fu_221_p2)
);

four_digit_counter_mul_14ns_16ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_14ns_16ns_29_1_1_U3(
    .din0(mul_ln65_fu_237_p0),
    .din1(mul_ln65_fu_237_p1),
    .dout(mul_ln65_fu_237_p2)
);

four_digit_counter_mul_14ns_16ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_14ns_16ns_29_1_1_U4(
    .din0(mul_ln68_fu_253_p0),
    .din1(mul_ln68_fu_253_p1),
    .dout(mul_ln68_fu_253_p2)
);

four_digit_counter_urem_11ns_5ns_4_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_11ns_5ns_4_15_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln1_reg_325),
    .din1(grp_fu_279_p1),
    .ce(1'b1),
    .dout(grp_fu_279_p2)
);

four_digit_counter_urem_8ns_5ns_4_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_8ns_5ns_4_12_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln60_1_reg_330),
    .din1(grp_fu_284_p1),
    .ce(1'b1),
    .dout(grp_fu_284_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == 1'b1))) begin
        counter <= next_counter_3_fu_198_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        next_counter_3_reg_319 <= next_counter_3_fu_198_p3;
        trunc_ln1_reg_325 <= {{mul_ln62_fu_221_p2[28:18]}};
        trunc_ln60_1_reg_330 <= {{mul_ln65_fu_237_p2[28:21]}};
        trunc_ln60_2_cast_reg_340 <= {{mul_ln68_fu_253_p2[27:24]}};
        trunc_ln60_2_reg_335 <= {{mul_ln68_fu_253_p2[28:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        select_ln70_reg_346 <= select_ln70_fu_299_p3;
        select_ln70_reg_346_pp0_iter10_reg <= select_ln70_reg_346_pp0_iter9_reg;
        select_ln70_reg_346_pp0_iter11_reg <= select_ln70_reg_346_pp0_iter10_reg;
        select_ln70_reg_346_pp0_iter12_reg <= select_ln70_reg_346_pp0_iter11_reg;
        select_ln70_reg_346_pp0_iter13_reg <= select_ln70_reg_346_pp0_iter12_reg;
        select_ln70_reg_346_pp0_iter14_reg <= select_ln70_reg_346_pp0_iter13_reg;
        select_ln70_reg_346_pp0_iter15_reg <= select_ln70_reg_346_pp0_iter14_reg;
        select_ln70_reg_346_pp0_iter16_reg <= select_ln70_reg_346_pp0_iter15_reg;
        select_ln70_reg_346_pp0_iter3_reg <= select_ln70_reg_346;
        select_ln70_reg_346_pp0_iter4_reg <= select_ln70_reg_346_pp0_iter3_reg;
        select_ln70_reg_346_pp0_iter5_reg <= select_ln70_reg_346_pp0_iter4_reg;
        select_ln70_reg_346_pp0_iter6_reg <= select_ln70_reg_346_pp0_iter5_reg;
        select_ln70_reg_346_pp0_iter7_reg <= select_ln70_reg_346_pp0_iter6_reg;
        select_ln70_reg_346_pp0_iter8_reg <= select_ln70_reg_346_pp0_iter7_reg;
        select_ln70_reg_346_pp0_iter9_reg <= select_ln70_reg_346_pp0_iter8_reg;
        urem_ln64_reg_356 <= grp_fu_279_p2;
        urem_ln67_reg_351 <= grp_fu_284_p2;
        urem_ln67_reg_351_pp0_iter14_reg <= urem_ln67_reg_351;
        urem_ln67_reg_351_pp0_iter15_reg <= urem_ln67_reg_351_pp0_iter14_reg;
        urem_ln67_reg_351_pp0_iter16_reg <= urem_ln67_reg_351_pp0_iter15_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_fu_156_p2 = (counter + 14'd1);

assign add_ln54_fu_184_p2 = ($signed(counter) + $signed(14'd16383));

assign add_ln70_fu_294_p2 = (trunc_ln60_2_cast_reg_340 + 4'd6);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign first_digit = grp_fu_206_p2[3:0];

assign fourth_digit = select_ln70_reg_346_pp0_iter16_reg;

assign grp_fu_206_p0 = ((down_count[0:0] == 1'b1) ? select_ln48_fu_190_p3 : next_counter_1_fu_170_p3);

assign grp_fu_206_p1 = 14'd10;

assign grp_fu_279_p1 = 11'd10;

assign grp_fu_284_p1 = 8'd10;

assign icmp_ln36_fu_150_p2 = ((counter == 14'd9999) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_178_p2 = ((counter == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_289_p2 = ((trunc_ln60_2_reg_335 < 5'd10) ? 1'b1 : 1'b0);

assign mul_ln62_fu_221_p0 = zext_ln62_fu_218_p1;

assign mul_ln62_fu_221_p1 = 29'd26215;

assign mul_ln65_fu_237_p0 = zext_ln62_fu_218_p1;

assign mul_ln65_fu_237_p1 = 29'd20972;

assign mul_ln68_fu_253_p0 = zext_ln62_fu_218_p1;

assign mul_ln68_fu_253_p1 = 29'd16778;

assign next_counter_1_fu_170_p3 = ((up_count[0:0] == 1'b1) ? select_ln36_fu_162_p3 : next_counter_fu_142_p3);

assign next_counter_3_fu_198_p3 = ((down_count[0:0] == 1'b1) ? select_ln48_fu_190_p3 : next_counter_1_fu_170_p3);

assign next_counter_fu_142_p3 = ((load[0:0] == 1'b1) ? counter_init_value : counter);

assign second_digit = urem_ln64_reg_356[3:0];

assign select_ln36_fu_162_p3 = ((icmp_ln36_fu_150_p2[0:0] == 1'b1) ? 14'd0 : add_ln42_fu_156_p2);

assign select_ln48_fu_190_p3 = ((icmp_ln48_fu_178_p2[0:0] == 1'b1) ? 14'd9999 : add_ln54_fu_184_p2);

assign select_ln70_fu_299_p3 = ((icmp_ln70_fu_289_p2[0:0] == 1'b1) ? trunc_ln60_2_cast_reg_340 : add_ln70_fu_294_p2);

assign third_digit = urem_ln67_reg_351_pp0_iter16_reg[3:0];

assign zext_ln62_fu_218_p1 = next_counter_3_reg_319;

endmodule //four_digit_counter
