-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bcd_counter_pipelining is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    pulse : IN STD_LOGIC_VECTOR (0 downto 0);
    seven_segment_data : OUT STD_LOGIC_VECTOR (7 downto 0);
    seven_segment_enable : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of bcd_counter_pipelining is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bcd_counter_pipelining_bcd_counter_pipelining,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.529000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=14,HLS_SYN_LUT=47,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal counter_state : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal seven_segment_code_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_ce0 : STD_LOGIC;
    signal seven_segment_code_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_counter_state_loc_0_phi_fu_86_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln16_fu_109_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_reg_pp0_iter0_counter_state_loc_0_reg_83 : STD_LOGIC_VECTOR (3 downto 0);
    signal pulse_read_read_fu_48_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln26_fu_124_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln16_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln22_fu_103_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bcd_counter_pipelining_seven_segment_code_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    seven_segment_code_U : component bcd_counter_pipelining_seven_segment_code_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => seven_segment_code_address0,
        ce0 => seven_segment_code_ce0,
        q0 => seven_segment_code_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((pulse_read_read_fu_48_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                counter_state <= select_ln16_fu_109_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln22_fu_103_p2 <= std_logic_vector(unsigned(counter_state) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_counter_state_loc_0_phi_fu_86_p4_assign_proc : process(counter_state, select_ln16_fu_109_p3, ap_phi_reg_pp0_iter0_counter_state_loc_0_reg_83, pulse_read_read_fu_48_p2)
    begin
        if ((pulse_read_read_fu_48_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_counter_state_loc_0_phi_fu_86_p4 <= counter_state;
        elsif ((pulse_read_read_fu_48_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_counter_state_loc_0_phi_fu_86_p4 <= select_ln16_fu_109_p3;
        else 
            ap_phi_mux_counter_state_loc_0_phi_fu_86_p4 <= ap_phi_reg_pp0_iter0_counter_state_loc_0_reg_83;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_counter_state_loc_0_reg_83 <= "XXXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;
    icmp_ln16_fu_97_p2 <= "1" when (counter_state = ap_const_lv4_9) else "0";
    pulse_read_read_fu_48_p2 <= pulse;
    select_ln16_fu_109_p3 <= 
        ap_const_lv4_0 when (icmp_ln16_fu_97_p2(0) = '1') else 
        add_ln22_fu_103_p2;
    seven_segment_code_address0 <= zext_ln26_fu_124_p1(4 - 1 downto 0);

    seven_segment_code_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            seven_segment_code_ce0 <= ap_const_logic_1;
        else 
            seven_segment_code_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    seven_segment_data <= seven_segment_code_q0;
    seven_segment_enable <= ap_const_lv4_E;
    zext_ln26_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_counter_state_loc_0_phi_fu_86_p4),64));
end behav;
