-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity display_float is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    acc : IN STD_LOGIC_VECTOR (31 downto 0);
    seven_segment_data : OUT STD_LOGIC_VECTOR (7 downto 0);
    seven_segment_enable : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of display_float is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "display_float_display_float,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.287000,HLS_SYN_LAT=39,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6057,HLS_SYN_LUT=5976,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_186A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000011000011010100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv32_41200000 : STD_LOGIC_VECTOR (31 downto 0) := "01000001001000000000000000000000";
    constant ap_const_lv65_19999999A : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000110011001100110011001100110011010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv29_A : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000001010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";

    signal state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal timer : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000011000011010100000";
    signal seven_segment_code_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_ce0 : STD_LOGIC;
    signal seven_segment_code_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal seven_segment_code_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_ce1 : STD_LOGIC;
    signal seven_segment_code_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal seven_segment_code_address2 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_ce2 : STD_LOGIC;
    signal seven_segment_code_q2 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_read_reg_679 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal acc_read_reg_679_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_read_reg_679_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_read_reg_679_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_read_reg_679_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_read_reg_679_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_read_reg_679_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_256_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_684 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_689 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_694 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_load_load_fu_322_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699 : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter24_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter25_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter26_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter27_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter28_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter29_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter30_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter31_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter32_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter33_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter34_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter35_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter36_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter37_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal state_load_reg_699_pp0_iter38_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal val_fu_400_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_reg_703 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln_reg_715 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_203_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_reg_720 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_185_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_reg_725 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_193_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter19_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter20_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter21_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter22_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter23_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter24_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_730_pp0_iter25_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_1_fu_443_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln342_1_reg_736 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_3_fu_457_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln71_2_fu_475_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln71_2_reg_746 : STD_LOGIC_VECTOR (8 downto 0);
    signal val_1_reg_751 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_reg_756 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter20_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter21_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter22_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter23_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter24_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter25_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter26_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter27_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter28_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter29_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter30_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter31_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter32_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter33_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter34_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter35_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter36_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_756_pp0_iter37_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_206_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv5_reg_761 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_189_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_1_reg_766 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_exp_2_reg_771 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln342_2_fu_556_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln342_2_reg_777 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_6_fu_587_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_787 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_792 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_reg_797 : STD_LOGIC_VECTOR (3 downto 0);
    signal seven_segment_code_load_1_reg_807 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter37 : STD_LOGIC := '0';
    signal seven_segment_code_load_1_reg_807_pp0_iter38_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln42_fu_666_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln42_reg_817 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter38 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter39 : STD_LOGIC := '0';
    signal ap_phi_mux_next_state_4_phi_fu_175_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln74_1_fu_379_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_next_state_4_reg_172 : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_3_fu_350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal next_state_2_fu_359_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln21_fu_374_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln27_fu_560_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln42_fu_652_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_fu_662_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln72_fu_670_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal next_timer_1_fu_342_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln42_1_fu_675_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_203_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_209_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_209_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal data_fu_214_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_228_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_232_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_218_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_246_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_250_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln71_fu_264_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln71_fu_270_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln71_fu_274_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln71_1_fu_282_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_fu_242_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln71_fu_286_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln71_fu_290_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln71_fu_296_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal next_state_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_timer_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal next_state_1_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_406_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_209_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal grp_fu_425_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal data_1_fu_430_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_exp_1_fu_433_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_1_fu_447_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_1_fu_451_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln71_1_fu_465_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln71_2_fu_471_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mantissa_1_fu_483_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln71_3_fu_496_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_1_fu_492_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln71_1_fu_499_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln71_1_fu_503_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln71_1_fu_509_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal select_ln71_3_fu_515_p3 : STD_LOGIC_VECTOR (78 downto 0);
    signal grp_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_2_fu_542_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_425_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mantissa_2_fu_565_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln317_2_fu_578_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_2_fu_581_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln71_2_fu_595_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln71_4_fu_600_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln71_4_fu_604_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln71_5_fu_612_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_2_fu_574_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln71_2_fu_616_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln71_2_fu_620_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln71_2_fu_626_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal grp_fu_406_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln71_5_fu_657_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_209_p00 : STD_LOGIC_VECTOR (64 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component display_float_fsub_32ns_32ns_32_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component display_float_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component display_float_uitofp_32ns_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component display_float_mul_32ns_34ns_65_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (33 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (64 downto 0) );
    end component;


    component display_float_urem_32ns_5ns_32_36_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component display_float_urem_29ns_5ns_29_33_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (28 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component display_float_seven_segment_code_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    seven_segment_code_U : component display_float_seven_segment_code_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => seven_segment_code_address0,
        ce0 => seven_segment_code_ce0,
        q0 => seven_segment_code_q0,
        address1 => seven_segment_code_address1,
        ce1 => seven_segment_code_ce1,
        q1 => seven_segment_code_q1,
        address2 => seven_segment_code_address2,
        ce2 => seven_segment_code_ce2,
        q2 => seven_segment_code_q2);

    fsub_32ns_32ns_32_7_full_dsp_1_U1 : component display_float_fsub_32ns_32ns_32_7_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_read_reg_679_pp0_iter6_reg,
        din1 => conv1_reg_720,
        ce => ap_const_logic_1,
        dout => grp_fu_185_p2);

    fsub_32ns_32ns_32_7_full_dsp_1_U2 : component display_float_fsub_32ns_32ns_32_7_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => dc_reg_730_pp0_iter25_reg,
        din1 => conv5_reg_761,
        ce => ap_const_logic_1,
        dout => grp_fu_189_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U3 : component display_float_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_reg_725,
        din1 => ap_const_lv32_41200000,
        ce => ap_const_logic_1,
        dout => grp_fu_193_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U4 : component display_float_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_1_reg_766,
        din1 => ap_const_lv32_41200000,
        ce => ap_const_logic_1,
        dout => grp_fu_198_p2);

    uitofp_32ns_32_6_no_dsp_1_U5 : component display_float_uitofp_32ns_32_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_203_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_203_p1);

    uitofp_32ns_32_6_no_dsp_1_U6 : component display_float_uitofp_32ns_32_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => val_1_reg_751,
        ce => ap_const_logic_1,
        dout => grp_fu_206_p1);

    mul_32ns_34ns_65_2_1_U7 : component display_float_mul_32ns_34ns_65_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_209_p0,
        din1 => grp_fu_209_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_209_p2);

    urem_32ns_5ns_32_36_1_U8 : component display_float_urem_32ns_5ns_32_36_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => val_reg_703,
        din1 => grp_fu_406_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_406_p2);

    urem_29ns_5ns_29_33_1_U9 : component display_float_urem_29ns_5ns_29_33_1
    generic map (
        ID => 1,
        NUM_STAGE => 33,
        din0_WIDTH => 29,
        din1_WIDTH => 5,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln_reg_715,
        din1 => grp_fu_425_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_425_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter37_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter37 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter38_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter38 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter39_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter39 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_read_reg_679 <= acc;
                acc_read_reg_679_pp0_iter1_reg <= acc_read_reg_679;
                state_load_reg_699 <= state;
                state_load_reg_699_pp0_iter1_reg <= state_load_reg_699;
                tmp_1_reg_694 <= shl_ln71_fu_296_p2(55 downto 24);
                tmp_2_reg_684 <= add_ln317_fu_250_p2(8 downto 8);
                tmp_reg_689 <= lshr_ln71_fu_290_p2(55 downto 24);
                val_reg_703 <= val_fu_400_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_read_reg_679_pp0_iter2_reg <= acc_read_reg_679_pp0_iter1_reg;
                acc_read_reg_679_pp0_iter3_reg <= acc_read_reg_679_pp0_iter2_reg;
                acc_read_reg_679_pp0_iter4_reg <= acc_read_reg_679_pp0_iter3_reg;
                acc_read_reg_679_pp0_iter5_reg <= acc_read_reg_679_pp0_iter4_reg;
                acc_read_reg_679_pp0_iter6_reg <= acc_read_reg_679_pp0_iter5_reg;
                b_1_reg_766 <= grp_fu_189_p2;
                b_reg_725 <= grp_fu_185_p2;
                c_reg_756 <= select_ln71_3_fu_515_p3(27 downto 24);
                c_reg_756_pp0_iter20_reg <= c_reg_756;
                c_reg_756_pp0_iter21_reg <= c_reg_756_pp0_iter20_reg;
                c_reg_756_pp0_iter22_reg <= c_reg_756_pp0_iter21_reg;
                c_reg_756_pp0_iter23_reg <= c_reg_756_pp0_iter22_reg;
                c_reg_756_pp0_iter24_reg <= c_reg_756_pp0_iter23_reg;
                c_reg_756_pp0_iter25_reg <= c_reg_756_pp0_iter24_reg;
                c_reg_756_pp0_iter26_reg <= c_reg_756_pp0_iter25_reg;
                c_reg_756_pp0_iter27_reg <= c_reg_756_pp0_iter26_reg;
                c_reg_756_pp0_iter28_reg <= c_reg_756_pp0_iter27_reg;
                c_reg_756_pp0_iter29_reg <= c_reg_756_pp0_iter28_reg;
                c_reg_756_pp0_iter30_reg <= c_reg_756_pp0_iter29_reg;
                c_reg_756_pp0_iter31_reg <= c_reg_756_pp0_iter30_reg;
                c_reg_756_pp0_iter32_reg <= c_reg_756_pp0_iter31_reg;
                c_reg_756_pp0_iter33_reg <= c_reg_756_pp0_iter32_reg;
                c_reg_756_pp0_iter34_reg <= c_reg_756_pp0_iter33_reg;
                c_reg_756_pp0_iter35_reg <= c_reg_756_pp0_iter34_reg;
                c_reg_756_pp0_iter36_reg <= c_reg_756_pp0_iter35_reg;
                c_reg_756_pp0_iter37_reg <= c_reg_756_pp0_iter36_reg;
                conv1_reg_720 <= grp_fu_203_p1;
                conv5_reg_761 <= grp_fu_206_p1;
                dc_reg_730 <= grp_fu_193_p2;
                dc_reg_730_pp0_iter18_reg <= dc_reg_730;
                dc_reg_730_pp0_iter19_reg <= dc_reg_730_pp0_iter18_reg;
                dc_reg_730_pp0_iter20_reg <= dc_reg_730_pp0_iter19_reg;
                dc_reg_730_pp0_iter21_reg <= dc_reg_730_pp0_iter20_reg;
                dc_reg_730_pp0_iter22_reg <= dc_reg_730_pp0_iter21_reg;
                dc_reg_730_pp0_iter23_reg <= dc_reg_730_pp0_iter22_reg;
                dc_reg_730_pp0_iter24_reg <= dc_reg_730_pp0_iter23_reg;
                dc_reg_730_pp0_iter25_reg <= dc_reg_730_pp0_iter24_reg;
                select_ln71_2_reg_746 <= select_ln71_2_fu_475_p3;
                seven_segment_code_load_1_reg_807_pp0_iter38_reg <= seven_segment_code_load_1_reg_807;
                state_load_reg_699_pp0_iter10_reg <= state_load_reg_699_pp0_iter9_reg;
                state_load_reg_699_pp0_iter11_reg <= state_load_reg_699_pp0_iter10_reg;
                state_load_reg_699_pp0_iter12_reg <= state_load_reg_699_pp0_iter11_reg;
                state_load_reg_699_pp0_iter13_reg <= state_load_reg_699_pp0_iter12_reg;
                state_load_reg_699_pp0_iter14_reg <= state_load_reg_699_pp0_iter13_reg;
                state_load_reg_699_pp0_iter15_reg <= state_load_reg_699_pp0_iter14_reg;
                state_load_reg_699_pp0_iter16_reg <= state_load_reg_699_pp0_iter15_reg;
                state_load_reg_699_pp0_iter17_reg <= state_load_reg_699_pp0_iter16_reg;
                state_load_reg_699_pp0_iter18_reg <= state_load_reg_699_pp0_iter17_reg;
                state_load_reg_699_pp0_iter19_reg <= state_load_reg_699_pp0_iter18_reg;
                state_load_reg_699_pp0_iter20_reg <= state_load_reg_699_pp0_iter19_reg;
                state_load_reg_699_pp0_iter21_reg <= state_load_reg_699_pp0_iter20_reg;
                state_load_reg_699_pp0_iter22_reg <= state_load_reg_699_pp0_iter21_reg;
                state_load_reg_699_pp0_iter23_reg <= state_load_reg_699_pp0_iter22_reg;
                state_load_reg_699_pp0_iter24_reg <= state_load_reg_699_pp0_iter23_reg;
                state_load_reg_699_pp0_iter25_reg <= state_load_reg_699_pp0_iter24_reg;
                state_load_reg_699_pp0_iter26_reg <= state_load_reg_699_pp0_iter25_reg;
                state_load_reg_699_pp0_iter27_reg <= state_load_reg_699_pp0_iter26_reg;
                state_load_reg_699_pp0_iter28_reg <= state_load_reg_699_pp0_iter27_reg;
                state_load_reg_699_pp0_iter29_reg <= state_load_reg_699_pp0_iter28_reg;
                state_load_reg_699_pp0_iter2_reg <= state_load_reg_699_pp0_iter1_reg;
                state_load_reg_699_pp0_iter30_reg <= state_load_reg_699_pp0_iter29_reg;
                state_load_reg_699_pp0_iter31_reg <= state_load_reg_699_pp0_iter30_reg;
                state_load_reg_699_pp0_iter32_reg <= state_load_reg_699_pp0_iter31_reg;
                state_load_reg_699_pp0_iter33_reg <= state_load_reg_699_pp0_iter32_reg;
                state_load_reg_699_pp0_iter34_reg <= state_load_reg_699_pp0_iter33_reg;
                state_load_reg_699_pp0_iter35_reg <= state_load_reg_699_pp0_iter34_reg;
                state_load_reg_699_pp0_iter36_reg <= state_load_reg_699_pp0_iter35_reg;
                state_load_reg_699_pp0_iter37_reg <= state_load_reg_699_pp0_iter36_reg;
                state_load_reg_699_pp0_iter38_reg <= state_load_reg_699_pp0_iter37_reg;
                state_load_reg_699_pp0_iter3_reg <= state_load_reg_699_pp0_iter2_reg;
                state_load_reg_699_pp0_iter4_reg <= state_load_reg_699_pp0_iter3_reg;
                state_load_reg_699_pp0_iter5_reg <= state_load_reg_699_pp0_iter4_reg;
                state_load_reg_699_pp0_iter6_reg <= state_load_reg_699_pp0_iter5_reg;
                state_load_reg_699_pp0_iter7_reg <= state_load_reg_699_pp0_iter6_reg;
                state_load_reg_699_pp0_iter8_reg <= state_load_reg_699_pp0_iter7_reg;
                state_load_reg_699_pp0_iter9_reg <= state_load_reg_699_pp0_iter8_reg;
                tmp_3_reg_741 <= add_ln317_1_fu_451_p2(8 downto 8);
                tmp_4_reg_792 <= lshr_ln71_2_fu_620_p2(27 downto 24);
                tmp_5_reg_797 <= shl_ln71_2_fu_626_p2(27 downto 24);
                tmp_6_reg_787 <= add_ln317_2_fu_581_p2(8 downto 8);
                trunc_ln342_1_reg_736 <= trunc_ln342_1_fu_443_p1;
                trunc_ln342_2_reg_777 <= trunc_ln342_2_fu_556_p1;
                trunc_ln42_reg_817 <= trunc_ln42_fu_666_p1;
                trunc_ln_reg_715 <= grp_fu_209_p2(64 downto 36);
                val_1_reg_751 <= select_ln71_3_fu_515_p3(55 downto 24);
                xs_exp_2_reg_771 <= data_2_fu_542_p1(30 downto 23);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter37 = ap_const_logic_1))) then
                seven_segment_code_load_1_reg_807 <= seven_segment_code_q2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                state <= ap_phi_mux_next_state_4_phi_fu_175_p8;
                timer <= next_timer_1_fu_342_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln317_1_fu_451_p2 <= std_logic_vector(unsigned(zext_ln317_1_fu_447_p1) + unsigned(ap_const_lv9_181));
    add_ln317_2_fu_581_p2 <= std_logic_vector(unsigned(zext_ln317_2_fu_578_p1) + unsigned(ap_const_lv9_181));
    add_ln317_fu_250_p2 <= std_logic_vector(unsigned(zext_ln317_fu_246_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter37, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_enable_reg_pp0_iter38, ap_enable_reg_pp0_iter39)
    begin
        if (((ap_enable_reg_pp0_iter39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter38 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0) and (ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 
    = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter37 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_next_state_4_phi_fu_175_p8_assign_proc : process(state_load_load_fu_322_p1, select_ln74_1_fu_379_p3, ap_phi_reg_pp0_iter0_next_state_4_reg_172, next_state_3_fu_350_p3, next_state_2_fu_359_p3, zext_ln21_fu_374_p1)
    begin
        if ((state_load_load_fu_322_p1 = ap_const_lv2_0)) then 
            ap_phi_mux_next_state_4_phi_fu_175_p8 <= zext_ln21_fu_374_p1;
        elsif ((state_load_load_fu_322_p1 = ap_const_lv2_1)) then 
            ap_phi_mux_next_state_4_phi_fu_175_p8 <= next_state_2_fu_359_p3;
        elsif ((state_load_load_fu_322_p1 = ap_const_lv2_2)) then 
            ap_phi_mux_next_state_4_phi_fu_175_p8 <= next_state_3_fu_350_p3;
        elsif ((state_load_load_fu_322_p1 = ap_const_lv2_3)) then 
            ap_phi_mux_next_state_4_phi_fu_175_p8 <= select_ln74_1_fu_379_p3;
        else 
            ap_phi_mux_next_state_4_phi_fu_175_p8 <= ap_phi_reg_pp0_iter0_next_state_4_reg_172;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_next_state_4_reg_172 <= "XX";
    ap_reset_idle_pp0 <= ap_const_logic_0;
    data_1_fu_430_p1 <= dc_reg_730;
    data_2_fu_542_p1 <= grp_fu_198_p2;
    data_fu_214_p1 <= acc;
    grp_fu_203_p0 <= 
        tmp_reg_689 when (tmp_2_reg_684(0) = '1') else 
        tmp_1_reg_694;
    grp_fu_209_p0 <= grp_fu_209_p00(32 - 1 downto 0);
    grp_fu_209_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_reg_703),65));
    grp_fu_209_p1 <= ap_const_lv65_19999999A(34 - 1 downto 0);
    grp_fu_406_p1 <= ap_const_lv32_A(5 - 1 downto 0);
    grp_fu_425_p1 <= ap_const_lv29_A(5 - 1 downto 0);
    lshr_ln71_1_fu_503_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_1_fu_492_p1),to_integer(unsigned('0' & zext_ln71_1_fu_499_p1(31-1 downto 0)))));
    lshr_ln71_2_fu_620_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_2_fu_574_p1),to_integer(unsigned('0' & zext_ln71_2_fu_616_p1(31-1 downto 0)))));
    lshr_ln71_fu_290_p2 <= std_logic_vector(shift_right(unsigned(zext_ln68_fu_242_p1),to_integer(unsigned('0' & zext_ln71_fu_286_p1(31-1 downto 0)))));
    mantissa_1_fu_483_p4 <= ((ap_const_lv1_1 & trunc_ln342_1_reg_736) & ap_const_lv1_0);
    mantissa_2_fu_565_p4 <= ((ap_const_lv1_1 & trunc_ln342_2_reg_777) & ap_const_lv1_0);
    mantissa_fu_232_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_228_p1) & ap_const_lv1_0);
    next_state_1_fu_368_p2 <= (next_state_fu_330_p2 xor ap_const_lv1_1);
    next_state_2_fu_359_p3 <= 
        ap_const_lv2_1 when (next_state_fu_330_p2(0) = '1') else 
        ap_const_lv2_2;
    next_state_3_fu_350_p3 <= 
        ap_const_lv2_2 when (next_state_fu_330_p2(0) = '1') else 
        ap_const_lv2_3;
    next_state_fu_330_p2 <= "0" when (timer = ap_const_lv32_0) else "1";
    next_timer_1_fu_342_p3 <= 
        next_timer_fu_336_p2 when (next_state_fu_330_p2(0) = '1') else 
        ap_const_lv32_186A0;
    next_timer_fu_336_p2 <= std_logic_vector(unsigned(timer) + unsigned(ap_const_lv32_FFFFFFFF));
    select_ln71_2_fu_475_p3 <= 
        sext_ln71_2_fu_471_p1 when (tmp_3_fu_457_p3(0) = '1') else 
        add_ln317_1_fu_451_p2;
    select_ln71_3_fu_515_p3 <= 
        lshr_ln71_1_fu_503_p2 when (tmp_3_reg_741(0) = '1') else 
        shl_ln71_1_fu_509_p2;
    select_ln71_4_fu_604_p3 <= 
        sext_ln71_4_fu_600_p1 when (tmp_6_fu_587_p3(0) = '1') else 
        add_ln317_2_fu_581_p2;
    select_ln71_5_fu_657_p3 <= 
        tmp_4_reg_792 when (tmp_6_reg_787(0) = '1') else 
        tmp_5_reg_797;
    select_ln71_fu_274_p3 <= 
        sext_ln71_fu_270_p1 when (tmp_2_fu_256_p3(0) = '1') else 
        add_ln317_fu_250_p2;
    select_ln74_1_fu_379_p3 <= 
        ap_const_lv2_3 when (next_state_fu_330_p2(0) = '1') else 
        ap_const_lv2_0;

    seven_segment_code_address0_assign_proc : process(state_load_reg_699_pp0_iter37_reg, ap_enable_reg_pp0_iter38, ap_block_pp0_stage0, zext_ln57_fu_662_p1, zext_ln72_fu_670_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter38 = ap_const_logic_1))) then
            if ((state_load_reg_699_pp0_iter37_reg = ap_const_lv2_3)) then 
                seven_segment_code_address0 <= zext_ln72_fu_670_p1(4 - 1 downto 0);
            elsif ((state_load_reg_699_pp0_iter37_reg = ap_const_lv2_2)) then 
                seven_segment_code_address0 <= zext_ln57_fu_662_p1(4 - 1 downto 0);
            else 
                seven_segment_code_address0 <= "XXXX";
            end if;
        else 
            seven_segment_code_address0 <= "XXXX";
        end if; 
    end process;

    seven_segment_code_address1 <= zext_ln42_fu_652_p1(4 - 1 downto 0);
    seven_segment_code_address2 <= zext_ln27_fu_560_p1(4 - 1 downto 0);

    seven_segment_code_ce0_assign_proc : process(ap_block_pp0_stage0_11001, state_load_reg_699_pp0_iter37_reg, ap_enable_reg_pp0_iter38)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter38 = ap_const_logic_1) and (state_load_reg_699_pp0_iter37_reg = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter38 = ap_const_logic_1) and (state_load_reg_699_pp0_iter37_reg = ap_const_lv2_2)))) then 
            seven_segment_code_ce0 <= ap_const_logic_1;
        else 
            seven_segment_code_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    seven_segment_code_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter37)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter37 = ap_const_logic_1))) then 
            seven_segment_code_ce1 <= ap_const_logic_1;
        else 
            seven_segment_code_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    seven_segment_code_ce2_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter36)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter36 = ap_const_logic_1))) then 
            seven_segment_code_ce2 <= ap_const_logic_1;
        else 
            seven_segment_code_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    seven_segment_data_assign_proc : process(seven_segment_code_q0, state_load_reg_699_pp0_iter38_reg, seven_segment_code_load_1_reg_807_pp0_iter38_reg, ap_enable_reg_pp0_iter39, ap_block_pp0_stage0_01001, zext_ln42_1_fu_675_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter39 = ap_const_logic_1) and (state_load_reg_699_pp0_iter38_reg = ap_const_lv2_0))) then 
            seven_segment_data <= seven_segment_code_load_1_reg_807_pp0_iter38_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter39 = ap_const_logic_1) and (state_load_reg_699_pp0_iter38_reg = ap_const_lv2_1))) then 
            seven_segment_data <= zext_ln42_1_fu_675_p1;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter39 = ap_const_logic_1) and (state_load_reg_699_pp0_iter38_reg = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter39 = ap_const_logic_1) and (state_load_reg_699_pp0_iter38_reg = ap_const_lv2_2)))) then 
            seven_segment_data <= seven_segment_code_q0;
        else 
            seven_segment_data <= "XXXXXXXX";
        end if; 
    end process;


    seven_segment_enable_assign_proc : process(state_load_reg_699_pp0_iter38_reg, ap_enable_reg_pp0_iter39, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter39 = ap_const_logic_1))) then
            if ((state_load_reg_699_pp0_iter38_reg = ap_const_lv2_3)) then 
                seven_segment_enable <= ap_const_lv4_E;
            elsif ((state_load_reg_699_pp0_iter38_reg = ap_const_lv2_0)) then 
                seven_segment_enable <= ap_const_lv4_7;
            elsif ((state_load_reg_699_pp0_iter38_reg = ap_const_lv2_1)) then 
                seven_segment_enable <= ap_const_lv4_B;
            elsif ((state_load_reg_699_pp0_iter38_reg = ap_const_lv2_2)) then 
                seven_segment_enable <= ap_const_lv4_D;
            else 
                seven_segment_enable <= "XXXX";
            end if;
        else 
            seven_segment_enable <= "XXXX";
        end if; 
    end process;

        sext_ln71_1_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_fu_274_p3),32));

        sext_ln71_2_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_1_fu_465_p2),9));

        sext_ln71_3_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_2_reg_746),32));

        sext_ln71_4_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_2_fu_595_p2),9));

        sext_ln71_5_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln71_4_fu_604_p3),32));

        sext_ln71_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln71_fu_264_p2),9));

    shl_ln71_1_fu_509_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_1_fu_492_p1),to_integer(unsigned('0' & zext_ln71_1_fu_499_p1(31-1 downto 0)))));
    shl_ln71_2_fu_626_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_2_fu_574_p1),to_integer(unsigned('0' & zext_ln71_2_fu_616_p1(31-1 downto 0)))));
    shl_ln71_fu_296_p2 <= std_logic_vector(shift_left(unsigned(zext_ln68_fu_242_p1),to_integer(unsigned('0' & zext_ln71_fu_286_p1(31-1 downto 0)))));
    state_load_load_fu_322_p1 <= state;
    sub_ln71_1_fu_465_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_1_fu_433_p4));
    sub_ln71_2_fu_595_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_2_reg_771));
    sub_ln71_fu_264_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_218_p4));
    tmp_2_fu_256_p3 <= add_ln317_fu_250_p2(8 downto 8);
    tmp_3_fu_457_p3 <= add_ln317_1_fu_451_p2(8 downto 8);
    tmp_6_fu_587_p3 <= add_ln317_2_fu_581_p2(8 downto 8);
    trunc_ln342_1_fu_443_p1 <= data_1_fu_430_p1(23 - 1 downto 0);
    trunc_ln342_2_fu_556_p1 <= data_2_fu_542_p1(23 - 1 downto 0);
    trunc_ln342_fu_228_p1 <= data_fu_214_p1(23 - 1 downto 0);
    trunc_ln42_fu_666_p1 <= seven_segment_code_q1(7 - 1 downto 0);
    val_fu_400_p3 <= 
        tmp_reg_689 when (tmp_2_reg_684(0) = '1') else 
        tmp_1_reg_694;
    xs_exp_1_fu_433_p4 <= data_1_fu_430_p1(30 downto 23);
    xs_exp_fu_218_p4 <= data_fu_214_p1(30 downto 23);
    zext_ln21_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(next_state_1_fu_368_p2),2));
    zext_ln27_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_425_p2),64));
    zext_ln317_1_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_1_fu_433_p4),9));
    zext_ln317_2_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_2_reg_771),9));
    zext_ln317_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_218_p4),9));
    zext_ln42_1_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln42_reg_817),8));
    zext_ln42_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_406_p2),64));
    zext_ln57_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_756_pp0_iter37_reg),64));
    zext_ln68_1_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_1_fu_483_p4),79));
    zext_ln68_2_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_2_fu_565_p4),79));
    zext_ln68_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_232_p4),79));
    zext_ln71_1_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_3_fu_496_p1),79));
    zext_ln71_2_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_5_fu_612_p1),79));
    zext_ln71_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln71_1_fu_282_p1),79));
    zext_ln72_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln71_5_fu_657_p3),64));
end behav;
