// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="parity_generator_parity_generator,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.912000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=30,HLS_VERSION=2023_2}" *)

module parity_generator (
        a,
        ap_return
);


input  [15:0] a;
output  [0:0] ap_return;

wire   [0:0] tmp_1_fu_74_p3;
wire   [0:0] empty_fu_62_p1;
wire   [0:0] xor_ln13_fu_178_p2;
wire   [0:0] tmp_fu_66_p3;
wire   [0:0] tmp_2_fu_82_p3;
wire   [0:0] tmp_3_fu_90_p3;
wire   [0:0] tmp_4_fu_98_p3;
wire   [0:0] tmp_5_fu_106_p3;
wire   [0:0] xor_ln13_3_fu_196_p2;
wire   [0:0] xor_ln13_2_fu_190_p2;
wire   [0:0] xor_ln13_4_fu_202_p2;
wire   [0:0] xor_ln13_1_fu_184_p2;
wire   [0:0] tmp_6_fu_114_p3;
wire   [0:0] tmp_7_fu_122_p3;
wire   [0:0] tmp_8_fu_130_p3;
wire   [0:0] tmp_9_fu_138_p3;
wire   [0:0] xor_ln13_7_fu_220_p2;
wire   [0:0] xor_ln13_6_fu_214_p2;
wire   [0:0] tmp_10_fu_146_p3;
wire   [0:0] tmp_11_fu_154_p3;
wire   [0:0] tmp_12_fu_162_p3;
wire   [0:0] tmp_13_fu_170_p3;
wire   [0:0] xor_ln13_10_fu_238_p2;
wire   [0:0] xor_ln13_9_fu_232_p2;
wire   [0:0] xor_ln13_11_fu_244_p2;
wire   [0:0] xor_ln13_8_fu_226_p2;
wire   [0:0] xor_ln13_12_fu_250_p2;
wire   [0:0] xor_ln13_5_fu_208_p2;
wire   [0:0] xor_ln13_13_fu_256_p2;
wire   [0:0] tmp_14_fu_262_p3;

assign empty_fu_62_p1 = a[0:0];

assign tmp_10_fu_146_p3 = a[32'd11];

assign tmp_11_fu_154_p3 = a[32'd12];

assign tmp_12_fu_162_p3 = a[32'd13];

assign tmp_13_fu_170_p3 = a[32'd14];

assign tmp_14_fu_262_p3 = a[32'd15];

assign tmp_1_fu_74_p3 = a[32'd2];

assign tmp_2_fu_82_p3 = a[32'd3];

assign tmp_3_fu_90_p3 = a[32'd4];

assign tmp_4_fu_98_p3 = a[32'd5];

assign tmp_5_fu_106_p3 = a[32'd6];

assign tmp_6_fu_114_p3 = a[32'd7];

assign tmp_7_fu_122_p3 = a[32'd8];

assign tmp_8_fu_130_p3 = a[32'd9];

assign tmp_9_fu_138_p3 = a[32'd10];

assign tmp_fu_66_p3 = a[32'd1];

assign xor_ln13_10_fu_238_p2 = (tmp_13_fu_170_p3 ^ tmp_12_fu_162_p3);

assign xor_ln13_11_fu_244_p2 = (xor_ln13_9_fu_232_p2 ^ xor_ln13_10_fu_238_p2);

assign xor_ln13_12_fu_250_p2 = (xor_ln13_8_fu_226_p2 ^ xor_ln13_11_fu_244_p2);

assign xor_ln13_13_fu_256_p2 = (xor_ln13_5_fu_208_p2 ^ xor_ln13_12_fu_250_p2);

assign xor_ln13_1_fu_184_p2 = (xor_ln13_fu_178_p2 ^ tmp_fu_66_p3);

assign xor_ln13_2_fu_190_p2 = (tmp_3_fu_90_p3 ^ tmp_2_fu_82_p3);

assign xor_ln13_3_fu_196_p2 = (tmp_5_fu_106_p3 ^ tmp_4_fu_98_p3);

assign xor_ln13_4_fu_202_p2 = (xor_ln13_3_fu_196_p2 ^ xor_ln13_2_fu_190_p2);

assign xor_ln13_5_fu_208_p2 = (xor_ln13_4_fu_202_p2 ^ xor_ln13_1_fu_184_p2);

assign xor_ln13_6_fu_214_p2 = (tmp_7_fu_122_p3 ^ tmp_6_fu_114_p3);

assign xor_ln13_7_fu_220_p2 = (tmp_9_fu_138_p3 ^ tmp_8_fu_130_p3);

assign xor_ln13_8_fu_226_p2 = (xor_ln13_7_fu_220_p2 ^ xor_ln13_6_fu_214_p2);

assign xor_ln13_9_fu_232_p2 = (tmp_11_fu_154_p3 ^ tmp_10_fu_146_p3);

assign xor_ln13_fu_178_p2 = (tmp_1_fu_74_p3 ^ empty_fu_62_p1);

assign ap_return = (xor_ln13_13_fu_256_p2 ^ tmp_14_fu_262_p3);

endmodule //parity_generator
